- platform: generic
  still_image_url: !secret dlink_camera_link
  username: !secret dlink_camera_username
  password: !secret dlink_camera_password

- platform: generic
  name: Driveway
  still_image_url: !secret andriod_camera_link
  username: !secret andriod_camera_username
  password: !secret andriod_camera_password
