homeassistant:
  name: -H-
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 264
  unit_system: metric
  time_zone: America/Toronto
  customize: !include_dir_merge_named customizations
  packages: !include_dir_named packages
group: !include groups.yaml
frontend:
http:
   api_password: !secret api_password
   base_url: !secret base_url
discovery:
  ignore:
    - netgear_router
conversation:
updater:
history:
logbook:
sun:
tts:
  platform: google
#purge the home-assistant_v2.db otherwise system will crash.
recorder:
 # db_url: postgres://@/homeassistant
  purge_days: 3

# Make some errors go away!
logger:
  default: error
  logs:
    homeassistant.components.switch.template: fatal
    homeassistant.components.switch.command_line: fatal

#zoneminder:
#  host: localhost
#  path: /zm/
#  path_zms: /zm/cgi-bin/nph-zms
#  username: !secret zoneminder_user
#  password: !secret zoneminder_pass

# Single Line Includes
input_boolean: !include input-boolean.yaml
scene: !include_dir_list scenes
script: !include_dir_merge_named script
shell_command: !include shell_commands.yaml
automation: !include_dir_merge_list automation
sensor: !include sensors.yaml
media_player: !include media_player.yaml
camera: !include camera.yaml
wemo: !include wemo.yaml
device_tracker: !include device_tracker.yaml
zone: !include_dir_list zones

#Components
android_ip_webcam:
- host: !secret android_ip_webcam_url
  name: Driveway
  port: 8036
  username: !secret andriod_camera_username
  password: !secret andriod_camera_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

notify:
  - platform: pushbullet
    name: justin
    api_key: !secret pushbullet_api_key

light:
  - platform: hue
    host: !secret philips_hue_ip

mqtt:
  broker: !secret mqtt_url
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_password

# PC On / OFF switches
switch 2: !include switch_pc_livingroom.yaml
switch 3: !include switch_pc_bedroom.yaml
switch 4: !include switch_pc_office.yaml

#Side Panels
panel_iframe:
  graph:
    title: Graph
    icon: mdi:vector-polyline
    url: !secret graph_url
  zoneminder:
    title: Zoneminder
    icon: mdi:camera
    url: !secret zm_url
  glances:
    title: System Monitor
    icon: mdi:biohazard
    url: !secret glances_url
