homeassistant:
  name: -H-
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 264
  unit_system: metric
  time_zone: America/Toronto
  customize: !include_dir_merge_named customizations
  packages: !include_dir_named packages
group: !include groups.yaml
frontend:
http:
   api_password: !secret api_password
   base_url: !secret base_url
updater:
discovery:
  ignore:
    - netgear_router
conversation:
history:
logbook:
sun:
tts:
  platform: google
#purge the home-assistant_v2.db otherwise system will crash.
recorder:
 # db_url: postgres://@/homeassistant
  purge_days: 3

# Make some errors go away!
logger:
  default: error
  logs:
    homeassistant.components.switch.template: fatal
    homeassistant.components.switch.command_line: fatal

mqtt:
  broker: 192.168.1.250
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_password

# Components
sensor: !include sensors.yaml
nest: !include nest.yaml
light: !include light.yaml
media_player: !include media_player.yaml
camera: !include camera.yaml
wemo: !include wemo.yaml
device_tracker: !include device_tracker.yaml
zone: !include_dir_list zones/
#zoneminder:
#  host: localhost
#  path: /zm/
#  path_zms: /zm/cgi-bin/nph-zms
#  username: !secret zoneminder_user
#  password: !secret zoneminder_pass

# Controls
#input_select: !include input-selects.yaml
#input_slider: !include input-sliders.yaml
input_boolean: !include input-boolean.yaml
# Automation
scene: !include_dir_list scenes
script: !include_dir_merge_named script
shell_command: !include shell_commands.yaml
notify: !include notify.yaml
automation: !include_dir_merge_list automation
# PC On / OFF switches
switch 2: !include switch_pc_livingroom.yaml
switch 3: !include switch_pc_bedroom.yaml
switch 4: !include switch_pc_office.yaml

#Side Panels
panel_iframe:
  graph:
    title: Graph
    icon: mdi:vector-polyline
    url: !secret graph_url
  zoneminder:
    title: Zoneminder
    icon: mdi:camera
    url: !secret zm_url
  glances:
    title: System Monitor
    icon: mdi:biohazard
    url: !secret glances_url
