###### Configuration
homeassistant:
  name: -H-
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 264
  unit_system: metric
  time_zone: America/Toronto
  customize: !include_dir_merge_named customizations
  packages: !include_dir_named packages
group: !include groups.yaml
frontend:
conversation:
updater:
history:
logbook:
sun:
discovery:
# Single Line Includes
scene: !include_dir_list scenes
zone: !include_dir_list zones

#Components
emulated_hue:
  #host_ip: 192.168.1.129
  #expose_by_default: false
  exposed_domains:
    - switch
    - script
    #- light
    #- input_boolean

logger:
  default: error
  logs:
    homeassistant.components.switch.template: fatal
    homeassistant.components.switch.command_line: fatal

http:
   api_password: !secret api_password
   base_url: !secret base_url

tts:
  platform: google

recorder:
  purge_days: 3

android_ip_webcam:
- host: !secret android_ip_webcam_url
  name: Driveway
  port: 8036
  username: !secret andriod_camera_username
  password: !secret andriod_camera_password

camera:
  - platform: generic
    still_image_url: !secret dlink_camera_link
    username: !secret dlink_camera_username
    password: !secret dlink_camera_password

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

notify:
  - platform: pushbullet
    name: justin
    api_key: !secret pushbullet_api_key

light:
  - platform: hue
    host: !secret philips_hue_ip

mqtt:
  broker: !secret mqtt_url
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_password

device_tracker:
  - platform: owntracks
  - platform: nmap_tracker
    hosts:
      - 192.168.1.129
      - 192.168.1.202
      - 192.168.1.13
      - 192.168.1.15
      - 192.168.1.99
      - 192.168.1.230
      - 192.168.1.231

wemo:
  static:
    - 192.168.1.200
    - 192.168.1.201
    - 192.168.1.202
    - 192.168.1.6
    - 192.168.1.204
    - 192.168.1.205

media_player:
  - platform: kodi
    host: !secret kodi_livingroom_ip
    port: !secret kodi_livingroom_port
    username: !secret kodi_livingroom_username
    password: !secret kodi_livingroom_password
    turn_off_action: shutdown
    name: kodi_livingroom
  - platform: cast
    host: 192.168.1.230
  - platform: cast
    host: 192.168.1.231
  - platform: kodi
    host: !secret kodi_bedroom_ip
    port: !secret kodi_bedroom_port
    name: kodi_bedroom
    turn_off_action: hibernate

#Side Panels
panel_iframe:
  zoneminder:
    title: Zoneminder
    icon: mdi:camera
    url: !secret zm_url
  glances:
    title: System Monitor
    icon: mdi:biohazard
    url: !secret glances_url
