###### Configuration
homeassistant:
  name: -H-
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 264
  unit_system: metric
  time_zone: America/Toronto
  customize: !include_dir_merge_named customizations
  packages: !include_dir_named packages
frontend:
conversation:
updater:
history:
logbook:
sun:
#discovery:
#Components
# google:
#  client_id: !secret google_client_id
#  client_secret: !secret google_secret

binary_sensor:
  - platform: flic
    host: 192.168.1.92

emulated_hue:
  #host_ip: 192.168.1.129
  expose_by_default: false
  exposed_domains:
    - switch
    #- script
    #- light
    #- input_boolean

logger:
  default: error
  #default: info
  logs:
    homeassistant.components.switch.template: fatal
    homeassistant.components.switch.command_line: fatal
    homeassistant.pywemo.ssdp: fatal

http:
   api_password: !secret api_password
   base_url: !secret base_url

tts:
  platform: google

recorder:
  db_url: !secret database

light:
  - platform: hue
    host: !secret philips_hue_ip

mqtt:
  broker: !secret mqtt_url
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

device_tracker:
  - platform: owntracks
  - platform: nmap_tracker
    hosts:
      - 192.168.1.129
      - 192.168.1.202
      - 192.168.1.13
      - 192.168.1.99
      - 192.168.1.230
      - 192.168.1.252
      - 192.168.1.92
      - 192.168.1.249
  - platform: ping
    hosts:
      chromecast_2: 192.168.1.231
      camera_driveway: 192.168.1.15
      access_point: 192.168.1.207
      living_room_pc: 192.168.1.76
      bedroom_pc: 192.168.1.96
      bedroom_pi: 192.168.1.21
wemo:
  static:
    - 192.168.1.200
    - 192.168.1.201
    - 192.168.1.202
    - 192.168.1.203
    - 192.168.1.204
    - 192.168.1.205
    - 192.168.1.206

media_player:
  - platform: kodi
    host: !secret kodi_livingroom_ip
    port: !secret kodi_livingroom_port
    username: !secret kodi_livingroom_username
    password: !secret kodi_livingroom_password
    turn_off_action: shutdown
    name: kodi_livingroom
  - platform: cast
    host: 192.168.1.230
  - platform: cast
    host: 192.168.1.231
  - platform: kodi
    host: !secret kodi_bedroom_ip
    port: !secret kodi_bedroom_port
    name: kodi_bedroom
    turn_off_action: hibernate
  - platform: kodi
    host: !secret kodi_bedroom_pi_ip
    port: !secret kodi_bedroom_pi_port
    name: kodi_bedroom_pi
    turn_off_action: hibernate
