###### Configuration
homeassistant:
  name: -H-
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 264
  unit_system: metric
  time_zone: America/Toronto
  customize: !include_dir_merge_named customizations
  packages: !include_dir_named packages
frontend:
conversation:
updater:
history:
logbook:
sun:
discovery:
    ignore:
      - netgear_router
#Components
#google:
#  client_id: !secret google_client_id
#  client_secret: !secret google_secret

emulated_hue:
  #host_ip: 192.168.1.129
  expose_by_default: false
  exposed_domains:
    - switch
    #- script
    #- light
    #- input_boolean

logger:
  default: error
  #default: info
  logs:
    homeassistant.components.switch.template: fatal
    homeassistant.components.switch.command_line: fatal
    homeassistant.pywemo.ssdp: fatal

http:
   api_password: !secret api_password
   base_url: !secret base_url

tts:
  platform: google

recorder:
  db_url: !secret database

# influxdb:
#   host: 127.0.0.1
#   username: !secret influx_user
#   password: !secret influx_pass
#android_ip_webcam:
#- host: !secret android_ip_webcam_url
#  name: Driveway
#  port: 8036
#  username: !secret andriod_camera_username
#  password: !secret andriod_camera_password
# zoneminder:
#   host: localhost
#   username: !secret zoneminder_user
#   password: !secret zoneminder_pass

camera:
  - platform: generic
    name: Baby Monitor
    still_image_url: !secret dlink_camera_link
    username: !secret dlink_camera_username
    password: !secret dlink_camera_password
  # - platform: zoneminder

nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

notify:
  - platform: pushbullet
    name: justin
    api_key: !secret pushbullet_api_key_justin
  - platform: pushbullet
    name: nicole
    api_key: !secret pushbullet_api_key_nicole
light:
  - platform: hue
    host: !secret philips_hue_ip

mqtt:
  broker: !secret mqtt_url
  port: !secret mqtt_port
  client_id: !secret mqtt_client_id
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery: true
  discovery_prefix: homeassistant

device_tracker:
  - platform: netgear
    host: !secret netgear_host
    username: !secret netgear_username
    password: !secret netgear_password
  - platform: owntracks
  - platform: nmap_tracker
    hosts:
      - 192.168.1.129
      - 192.168.1.202
      - 192.168.1.13
      - 192.168.1.99
      - 192.168.1.230
      - 192.168.1.252
  - platform: ping
    hosts:
      chromecast_2: 192.168.1.231
      camera_driveway: 192.168.1.15
      access_point: 192.168.1.59
      living_room_pc: 192.168.1.76
      bedroom_pc: 192.168.1.96
      bedroom_pi: 192.168.1.21
wemo:
  static:
    - 192.168.1.200
    - 192.168.1.201
    - 192.168.1.202
    - 192.168.1.203
    - 192.168.1.204
    - 192.168.1.205

media_player:
  - platform: kodi
    host: !secret kodi_livingroom_ip
    port: !secret kodi_livingroom_port
    username: !secret kodi_livingroom_username
    password: !secret kodi_livingroom_password
    turn_off_action: shutdown
    name: kodi_livingroom
  - platform: cast
    host: 192.168.1.230
  - platform: cast
    host: 192.168.1.231
  - platform: kodi
    host: !secret kodi_bedroom_ip
    port: !secret kodi_bedroom_port
    name: kodi_bedroom
    turn_off_action: hibernate
  - platform: kodi
    host: !secret kodi_bedroom_pi_ip
    port: !secret kodi_bedroom_pi_port
    name: kodi_bedroom_pi
    turn_off_action: hibernate

#Side Panels
panel_iframe:
  zoneminder:
    title: Zoneminder
    icon: mdi:camera
    url: !secret zm_url
  glances:
    title: System Monitor
    icon: mdi:biohazard
    url: !secret glances_url
