#Views------------------------------------------------------------------
default_view:
  name: DEFAULT
  view: yes
  icon: mdi:home
  entities:
    - group.livingroom
    - group.bedroom
    - group.findlays_room
    - group.office
    - group.backyard
    - group.automation
sensor_view:
  name: Sensors
  view: yes
  icon: mdi:gauge
  entities:
    - group.presence
    - group.thermostat
    - group.all_temps
    - group.all_humidity
    - group.smoke_gas
    - group.motion_sensors
media_view:
  name: Media Players
  view: yes
  icon: mdi:kodi
  entities:
    - group.playlist
    - group.media_player_all
camera_view:
  name: Cameras
  view: yes
  icon: mdi:camera
  entities:
    - group.all_cameras
misc_view:
  name: Misc
  view: yes
  icon: mdi:power
  entities:
    - group.sensor_battery_levels
    #- group.sensor_homeserver
    - group.utilities
    - group.device_status
#Groups------------------------------------------------------------------
livingroom:
  name: Living Room
  entities:
   - switch.copy
   - light.living_room
   - script.lr_concentrate
   - script.lr_read
   - script.lr_relax
   - script.lr_dimmed
   - script.lr_springblossom
bedroom:
  name: Master Bedroom
  entities:
   - switch.copy3
   - switch.bedroom_lamps_
   - switch.bedroom_fan
findlays_room:
  name: Findlay's Room
  entities:
    - light.findlay_lamp
    - sensor.findlay_room_temperature
    - sensor.findlay_room_lux
    - sensor.findlay_room_motion
office:
  name: Office
  entities:
   - switch.copy4
   - switch.office_lightswitch
   - switch.office_led_strip
   - input_select.led_scene
   - input_select.led_color
backyard:
  name: Backyard
  entities:
    - light.deck_lights
    - switch.patio_amplifier
    - script.backyard_party
automation:
  name: Automations
  entities:
    - automation.night_light
    - script.good_morning
    - script.auto_all_tv
    - script.auto_cartoons
    - script.auto_pawpatrol
presence:
  name: Presence
  entities:
   - device_tracker.bigdrakar_justin
   - device_tracker.bigdrakar_nicole
   - input_boolean.guest
   - input_boolean.away
   - input_boolean.vacation
weather:
  name: Weather
  entities:
    - sensor.dark_sky_temperature
    - sensor.dark_sky_humidity
  #  - sensor.dark_sky_daily_summary
  # - sensor.dark_sky_apparent_temperature
  # - sensor.dark_sky_cloud_coverage
  # - sensor.dark_sky_daily_high_apparent_temperature
  # - sensor.dark_sky_daily_high_temperature
  # - sensor.dark_sky_daily_low_apparent_temperature
  # - sensor.dark_sky_daily_low_temperature
  # - sensor.dark_sky_daily_max_precip_intensity
  # - sensor.dark_sky_dew_point
  # - sensor.dark_sky_hourly_summary
  # - sensor.dark_sky_icon
  # - sensor.dark_sky_minutely_summary
  # - sensor.dark_sky_nearest_storm_bearing
  # - sensor.dark_sky_nearest_storm_distance
  # - sensor.dark_sky_ozone
  # - sensor.dark_sky_precip
  # - sensor.dark_sky_precip_intensity
  # - sensor.dark_sky_pressure
  # - sensor.dark_sky_summary
  # - sensor.dark_sky_visibility
  # - sensor.dark_sky_wind_bearing
  #  - sensor.dark_sky_wind_speed
  #  - sun.sun
  # - sensor.yr_symbol
  # - sensor.dark_sky_precip_probability
thermostat:
  name: Thermostat
  entities:
   - climate.hallway
   - binary_sensor.hallway_thermostat_fan
   - sensor.hallway_thermostat_hvac_state
   - sensor.hallway_thermostat_operation_mode
motion_sensors:
  name: Motion Sensors
  entities:
   - sensor.findlay_room_motion
   - sensor.living_room_motion
   - sensor.dining_room_motion
all_temps:
  name: Temperature
  entities:
   - sensor.dark_sky_temperature
   - sensor.hallway_thermostat_temperature
   - sensor.findlay_room_temperature
   - sensor.living_room_temperature
   - sensor.dining_room_temperature
   - sensor.average_house_temp
all_humidity:
  name: Humidity
  entities:
    - sensor.dark_sky_humidity
    - sensor.hallway_thermostat_humidity
    - sensor.mold_indicator
    - switch.dehumidifier
    - automation.turn_on_dehumidifier_if_mold_sensor_is_high
all_cameras:
  name: Cameras
  entities:
   - camera.baby_monitor
   - camera.driveway
smoke_gas:
  name: "Smoke & CO"
  entities:
    - binary_sensor.kitchen_nest_protect_online
    - sensor.kitchen_nest_protect_co_status
    - sensor.kitchen_nest_protect_smoke_status
sensor_battery_levels:
  name: Battery Levels
  entities:
   - sensor.findlay_room_motion_sensor_battery_level
   - sensor.living_room_motion_sensor_battery_level
   - sensor.dining_room_motion_sensor_battery_level
   - sensor.findlays_room_dimmer_switch
   - sensor.living_room_dimmer_switch
   - sensor.kitchen_nest_protect_battery_health
   - sensor.justins_g5_battery
   - sensor.nicoles_s7_battery
playlist:
  name: Radio
  entities:
    - input_select.radio_station_location
    - input_select.radio_station
    - input_slider.volume_radio
media_player_all:
  name: Media Players
  entities:
    - media_player.kodi_livingroom
    - media_player.kodi_bedroom
    - media_player.kitchen
    - media_player.backyard
    - media_player.home_group
utilities:
  name: Utilities
  entities:
    - script.refresh_devices
    - script.restart_ha
    - script.update_ha
device_status:
  name: Device Status
  entities:
    - sensor.access_point
    - sensor.wemo_link
    - sensor.philips_hue_hub
    - sensor.chromecast_backyard
    - sensor.chromecast_kitchen
    - sensor.dlink_camera
    - sensor.driveway_camera
