- platform: kodi
  host: !secret kodi_livingroom_ip
  port: !secret kodi_livingroom_port
  username: !secret kodi_livingroom_username
  password: !secret kodi_livingroom_password
  turn_off_action: shutdown
  name: kodi_livingroom
- platform: cast
  host: 192.168.1.230
- platform: cast
  host: 192.168.1.231
- platform: kodi
  host: !secret kodi_bedroom_ip
  port: !secret kodi_bedroom_port
  name: kodi_bedroom
  turn_off_action: hibernate
