alias: Kitchen Radio
trigger:
  platform: state
  entity_id: input_select.radio_station
action:
  service: script.turn_on
  data_template:
    entity_id: >
    service: media_player.play_media
    data_template:
      entity_id: >
        {% if input_select.location == 'Kitchen' %}
          media_player.kitchen
        {%-elif input_select.location == 'Backyard' %}
          media_player.backyard
        {% endif %}
      media_content_id: >
        {% if input_select.radio_station == 'Hot108' %}
          "http://jbmedia-edge1.cdnstream.com:80/hot108"
        {%-elif input_select.radio_station == 'The Beat' %}
          "http://live.leanstream.co/CKBTFM-MP3"
        {% endif %}
      media_content_type: 'audio/mp3'
