alias: Notify If Nicole Left Work
trigger:
  platform: state
  entity_id: device_tracker.bigdrakar_nicole
  from: 'Work - Westmount'
  to: 'not_home'
action:
  service: notify.justin
  data:
    message: 'Nicole has left Work'
