- alias: 'Set Radio Volume'
  trigger:
    - platform: state
      entity_id: input_slider.volume_radio
  action:
    - service: media_player.volume_set
      data_template:
        entity_id: >
          {% if is_state("input_select.radio_station_location", "Kitchen") %} media_player.kitchen
          {% elif is_state("input_select.radio_station_location", "Backyard") %} media_player.backyard
          {% endif %}
        volume_level: '{{  states.input_slider.volume_radio.state  }}'
