alias: Scene Living Room
trigger:
  platform: state
  entity_id: input_select.scene_livingroom
action:
  - service: scene.turn_on
    data_template:
      entity_id: >
        {% if is_state( "input_select.scene_livingroom", "Nightlight" ) %}
          scene.livingroom_nightlight
        {%-elif is_state( "input_select.scene_livingroom", "Dimmed" ) %}
          scene.livingroom_dimmed
        {%-elif is_state( "input_select.scene_livingroom", "Relax" ) %}
          scene.livingroom_relax
        {%-elif is_state( "input_select.scene_livingroom", "Read" ) %}
          scene.livingroom_read
        {%-elif is_state( "input_select.scene_livingroom", "Bright" ) %}
          scene.livingroom_concentrate
        {%-elif is_state( "input_select.scene_livingroom", "Off" ) %}
          scene.livingroom_off
        {% endif %}
  - service: input_select.select_option
    data:
      entity_id: input_select.scene_livingroom
      option: "-"
