alias: Trigger Alarm
trigger:
- platform: state
  entity_id: sensor.findlay_room_motion
  to: 'True'
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: 'input_boolean.away'
      state: 'on'
    - condition: state
      entity_id: 'input_boolean.vacation'
      state: 'on'
action:
- service: script.activate_alarm
