################################################################
## Packages / Alexa Scripts
################################################################
homeassistant:
  customize:
    script.kitchen_radio:
      friendly_name: Kitchen Radio
      icon: mdi:music-note

script:
###### ALEXA TURN ON KITCHEN RADIO
  kitchen_radio:
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.kitchen
          volume_level: '0.35'
      - service: media_player.play_media
        data_template:
          entity_id: media_player.kitchen
          media_content_id: http://rfcmedia.streamguys1.com/90hits.mp3
          media_content_type: 'audio/mp3'

###### ALEXA TURN ON BABY CAM
  baby_cam:
    sequence:
      - service: shell_command.baby_cam

###### ALEXA TURN ON HOT / COLD
  hotter:
    sequence:
      - service: climate.set_temperature
        data_template:
          entity_id: climate.hallway
          temperature: "{{ (states.climate.hallway.attributes.current_temperature | float) +1 }}"
  colder:
    sequence:
      - service: climate.set_temperature
        data_template:
          entity_id: climate.hallway
          temperature: "{{ (states.climate.hallway.attributes.current_temperature | float) -1 }}"

###### ALEXA TURN OFF CHROMECAST
  chromecast:
    sequence:
      - service: media_player.turn_off
        entity_id: media_player.backyard
      - service: media_player.turn_off
        entity_id: media_player.kitchen

###### ALEXA TURN ON or OFF PC (Living Room)
  pc:
    sequence:
      - service: switch.toggle
        entity_id: switch.living_room_pc

###### ALEXA TURN ON or OFF BEDROOM PC
  bedroom_pc:
    sequence:
      - service: switch.toggle
        entity_id: switch.bedroom_pc

###### ALEXA TURN ON or OFF OFFICE PC
  office_pc:
    sequence:
      - service: switch.toggle
        entity_id: switch.office_pc

shell_command:
  baby_cam: 'bash /home/homeassistant/.homeassistant/shell/baby_cam.sh'
