################################################################
## Packages / Alexa Scripts
################################################################
homeassistant:
  customize:
    script.kitchen_radio:
      friendly_name: Kitchen Radio
      icon: mdi:music-note

script:
  kitchen_radio:
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.kitchen
          volume_level: '0.35'
      - service: media_player.play_media
        data_template:
          entity_id: media_player.kitchen
          media_content_id: http://rfcmedia.streamguys1.com/90hits.mp3
          media_content_type: 'audio/mp3'
