################################################################
## Packages / Alexa Scripts
################################################################
homeassistant:
  customize:
    script.kitchen_radio:
      emulated_hue: true
      friendly_name: 'Kitchen Radio'
    script.hotter:
      emulated_hue: true
      friendly_name: 'Hotter'
    script.colder:
      emulated_hue: true
      friendly_name: 'Colder'
    script.fan:
      emulated_hue: true
      friendly_name: 'Fan'
    script.pc:
      emulated_hue: true
      friendly_name: 'PC'
    script.bedroom_pc:
      emulated_hue: true
      friendly_name: 'Bedroom PC'
    script.office_pc:
      emulated_hue: true
      friendly_name: 'Office PC'

script:
###### ALEXA TURN ON/OFF KITCHEN RADIO
  kitchen_radio:
    sequence:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state('media_player.kitchen', 'off') %} script.kitchen_radio_off
            {% elif not is_state('media_player.kitchen', 'off') %} script.kitchen_radio_on
            {% endif %}
  kitchen_radio_off:
    sequence:
      - service: media_player.volume_set
        data:
          entity_id: media_player.kitchen
          volume_level: '0.35'
      - service: media_player.play_media
        data_template:
          entity_id: media_player.kitchen
          media_content_id: http://rfcmedia.streamguys1.com/90hits.mp3
          media_content_type: 'audio/mp3'
  kitchen_radio_on:
    sequence:
      - service: media_player.turn_off
        entity_id: media_player.kitchen

###### ALEXA TURN ON or OFF PC (Living Room)
  pc:
    sequence:
      - service: switch.toggle
        entity_id: switch.living_room_pc

###### ALEXA TURN ON or OFF BEDROOM PC
  bedroom_pc:
    sequence:
      - service: switch.toggle
        entity_id: switch.bedroom_pc

###### ALEXA TURN ON or OFF OFFICE PC
  office_pc:
    sequence:
      - service: switch.toggle
        entity_id: switch.office_pc

shell_command:
  baby_cam: 'bash /home/homeassistant/.homeassistant/shell/baby_cam.sh'
