################################################################
## Packages / Auto Playlists
################################################################
homeassistant:
  customize:
    script.auto_cartoons:
      friendly_name: Cartoons
      icon: mdi:playlist-play
    script.auto_all_tv:
      friendly_name: All TV
      icon: mdi:playlist-play
    script.auto_pawpatrol:
      friendly_name: Paw Partol
      icon: mdi:playlist-play

script:
###### LIVING ROOM CARTOONS
  auto_cartoons:
    sequence:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state('switch.living_room_pc', 'off') %} script.auto_cartoons_off
            {% elif is_state('switch.living_room_pc', 'on') %} script.auto_cartoons_on
            {% endif %}
  auto_cartoons_off:
    sequence:
      #turn on computer/tv/reciever
      - service: switch.turn_on
        entity_id: switch.living_room_pc
      #wait the time it takes to boot computer and load KODI
      - delay:
          minutes: 1
          seconds: 30
      # json curl to play all cartoons smart playlist
      - service: shell_command.curl
        data:
          url: "http://192.168.1.76:8099/jsonrpc"
          method: "post"
          headers:
            content-type: "application/json"
          payload:
            jsonrpc: "2.0"
            id: "1"
            method: "Player.Open"
            params:
              item:
                file: "c:/Users/Living Room/AppData/Roaming/Kodi/userdata/playlists/video/cartoon2.xsp"
  auto_cartoons_on:
    sequence:
      - service: shell_command.curl
        data:
          url: "http://192.168.1.76:8099/jsonrpc"
          method: "post"
          headers:
            content-type: "application/json"
          payload:
            jsonrpc: "2.0"
            id: "1"
            method: "Player.Open"
            params:
              item:
                file: "c:/Users/Living Room/AppData/Roaming/Kodi/userdata/playlists/video/cartoon2.xsp"

###### LIVING ROOM ALL TV
  auto_all_tv:
    sequence:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state('switch.living_room_pc', 'off') %} script.all_tv_off
            {% elif is_state('switch.living_room_pc', 'on') %} script.all_tv_on
            {% endif %}
  all_tv_off:
    sequence:
      #turn on computer/tv/reciever
      - service: switch.turn_on
        entity_id: switch.living_room_pc
      #wait the time it takes to boot computer and load KODI
      - delay:
          minutes: 1
          seconds: 30
      # json curl to play all cartoons smart playlist
      - service: shell_command.curl
        data:
          url: "http://192.168.1.76:8099/jsonrpc"
          method: "post"
          headers:
            content-type: "application/json"
          payload:
            jsonrpc: "2.0"
            id: "1"
            method: "Player.Open"
            params:
              item:
                file: "c:/Users/Living Room/AppData/Roaming/Kodi/userdata/playlists/video/all.xsp"
  all_tv_on:
    sequence:
      - service: shell_command.curl
        data:
          url: "http://192.168.1.76:8099/jsonrpc"
          method: "post"
          headers:
            content-type: "application/json"
          payload:
            jsonrpc: "2.0"
            id: "1"
            method: "Player.Open"
            params:
              item:
                file: "c:/Users/Living Room/AppData/Roaming/Kodi/userdata/playlists/video/all.xsp"

###### LIVINGROOM PAW PATROLL
  auto_pawpatrol:
    sequence:
      - service: script.turn_on
        data_template:
          entity_id: >
            {% if is_state('switch.living_room_pc', 'off') %} script.auto_pawpatrol_off
            {% elif is_state('switch.living_room_pc', 'on') %} script.auto_pawpatrol_on
            {% endif %}
  auto_pawpatrol_off:
    sequence:
      #turn on computer/tv/reciever
      - service: switch.turn_on
        entity_id: switch.living_room_pc
      #wait the time it takes to boot computer and load KODI
      - delay:
          minutes: 1
          seconds: 30
      # json curl to play all cartoons smart playlist
      - service: shell_command.curl
        data:
          url: "http://192.168.1.76:8099/jsonrpc"
          method: "post"
          headers:
            content-type: "application/json"
          payload:
            jsonrpc: "2.0"
            id: "1"
            method: "Player.Open"
            params:
              item:
                file: "c:/Users/Living Room/AppData/Roaming/Kodi/userdata/playlists/video/pawpatrol.xsp"
  auto_pawpatrol_on:
    sequence:
      - service: shell_command.curl
        data:
          url: "http://192.168.1.76:8099/jsonrpc"
          method: "post"
          headers:
            content-type: "application/json"
          payload:
            jsonrpc: "2.0"
            id: "1"
            method: "Player.Open"
            params:
              item:
                file: "c:/Users/Living Room/AppData/Roaming/Kodi/userdata/playlists/video/pawpatrol.xsp"
  play:
    sequence:
      - service: shell_command.play
  stop:
    sequence:
      - service: shell_command.stop
  next:
    sequence:
      - service: shell_command.next
  pause:
    sequence:
      - service: shell_command.curl
        data:
          url: "http://192.168.1.76:8099/jsonrpc"
          method: "post"
          headers:
            content-type: "application/json"
          payload:
            jsonrpc: "2.0"
            method: "Player.PlayPause"
            id: 1
            params:
              playerid: 1

shell_command:
  play: 'bash /home/homeassistant/.homeassistant/shell/play.sh'
  stop: 'bash /home/homeassistant/.homeassistant/shell/stop.sh'
  next: 'bash /home/homeassistant/.homeassistant/shell/next.sh'
  #pause: 'bash /home/homeassistant/.homeassistant/shell/pause.sh'
