################################################################
## Packages / Master Bedroom
################################################################
homeassistant:
  customize:
    switch.white_noise:
      friendly_name: 'White Noise'
      icon: mdi:snowflake
    media_player.kodi_bedroom:
      friendly_name: Bedroom KODI
    media_player.kodi_bedroom_pi:
      friendly_name: Bedroom KODI PI

###### STATE CARD
group:
  bedroom:
    name: Master Bedroom
    entities:
     - switch.bedroom_pc
     - switch.bedroom_lamps_
     - switch.bedroom_fan
     - switch.white_noise
     - switch.led_strip
     - input_select.led_scene
     - input_select.led_color
     - switch.bedroom_tv
     - switch.bedroom_media

sensor:
  - platform: template
    sensors:
      white_noise:
        value_template: "{% if is_state('media_player.kodi_bedroom_pi', 'playing') %}on{% else %}Off{% endif %}"

switch:
  - platform: template
    switches:
      white_noise:
        value_template: '{{ states.sensor.white_noise.state }}'
        turn_on:
          service: script.turn_on
          entity_id: script.blizzard
        turn_off:
          service: media_player.media_Stop
          entity_id: media_player.kodi_bedroom_pi

script:
  blizzard:
    sequence:
      - service: media_player.play_media
        data:
          entity_id: media_player.kodi_bedroom_pi
          media_content_id: "http://192.168.1.250:8123/local/blizzard.mp3"
          media_content_type: "audio/mp3"
