################################################################
## Packages / Camera
################################################################
homeassistant:
   customize:
    script.notify_camera:
      friendly_name: Email Camera Photo
    script.start_gifmaker:
      friendly_name: Start Gif Maker
    sensor.gif_maker_cpu:
      friendly_name: Gif Maker CPU Usage
    sensor.gif_maker_status:
      friendly_name: Gif Maker
      icon: mdi:memory

###### STATE CARD
group:
  all_cameras:
    name: Cameras
    control: hidden
    entities:
     - camera.findlay
     - camera.driveway
  camera_control:
    name: Camera Controls
    control: hidden
    entities:
     - script.notify_camera
     - script.start_gifmaker
     - sensor.gif_maker_cpu
     - sensor.gif_maker_status
     - sensor.driveway_events
     - sensor.driveway_status
     - sensor.findlay_events
     - sensor.findlay_status

zoneminder:
  host: !secret zm_host
  username: !secret zm_username
  password: !secret zm_password

camera:
  - platform: zoneminder

  # - platform: generic
  #   name: Baby Monitor
  #   still_image_url: !secret dlink_camera_link
  #   username: !secret dlink_camera_username
  #   password: !secret dlink_camera_password
  #
  # - platform: mjpeg
  #   name: Driveway
  #   mjpeg_url: !secret dlink2_camera_mjpeg
  #   still_image_url: !secret dlink2_camera_link
  #   username: !secret dlink2_camera_username
  #   password: !secret dlink2_camera_password

automation:
  - alias: driveway_motion_detected
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.driveway_events
    condition:
      - condition: state
        entity_id: input_boolean.away
        state: 'on'
    action:
      - service: notify.html5
        data:
          message: "Motion Detected in the Driveway"
          target: "justin"

  - alias: 'Auto Start Gif Maker'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: automation.startup_workaround
        from: 'on'
        to: 'off'
    action:
      - service: script.start_gifmaker

  - alias: 'Auto Restart Gif Maker'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.gif_maker_status
        from: 'on'
        to: 'off'
    action:
      - service: script.start_gifmaker

script:
  start_gifmaker:
    sequence:
      - service: shell_command.start_gifmaker
  notify_camera:
    sequence:
      - service: shell_command.clear_images
      - service: shell_command.driveway
      - service: shell_command.driveway2
      - delay: '00:00:30'
      - service: shell_command.push_image

sensor:
  - platform: zoneminder
    include_archived: false
###### GET CPU USAGE OF THE GIF MAKER SCRIPT
  - platform: command_line
    command: ps -eo pcpu -eo command |grep python |grep buffer.py
    name: gif_maker_cpu
    value_template: '{{value [0:4]|float}}'
    unit_of_measurement: '%'
###### CREATE STATUS SENSOR TO USE IN AUTOMATION
  - platform: template
    sensors:
      gif_maker_status:
        value_template: >-
          {%- if states.sensor.gif_maker_cpu.state | float == 0.0 -%}
            off
          {% else %}
            on
          {% endif %}

shell_command:
  clear_images: rm /home/homeassistant/.homeassistant/www/camera_shots/*
  push_image: 'bash /home/homeassistant/.homeassistant/shell/push_image.sh'
  start_gifmaker: bash /home/homeassistant/.homeassistant/shell/gif_maker.sh
  driveway: !secret driveway_camera_photo_url
  driveway2: curl -o /home/homeassistant/.homeassistant/www/camera_shots/drive1.gif "localhost:8080/gif?camera=drive1&duration=60&interval=0.25"
