################################################################
## Packages / Device Status
################################################################
homeassistant:
  customize:
    #ONLINE / OFFLINE Device Tracker
    sensor.access_point:
      friendly_name: Access Point
      icon: mdi:router-wireless
    sensor.wemo_link:
      friendly_name: Wemo Link
      entity_picture: /local/wemo.png
    sensor.philips_hue_hub:
      friendly_name: Philips Hue Hub
      entity_picture: /local/huebridge.png
    sensor.chromecast_kitchen:
      friendly_name: Chromecast Kitchen
      entity_picture: /local/chromecast.png
    sensor.chromecast_backyard:
      friendly_name: Chromecast Backyard
      entity_picture: /local/chromecast.png
    sensor.dlink_camera:
      friendly_name: Baby Monitor
      icon: mdi:camera
    sensor.driveway_camera:
      friendly_name: Driveway Camera
      icon: mdi:camera
    sensor.raspberry_pi:
      friendly_name: 'Raspberry Pi'
      icon: mdi:chip
###### STATE CARD
group:
  device_status:
    name: Device Status
    entities:
      - sensor.access_point
      - sensor.wemo_link
      - sensor.philips_hue_hub
      - sensor.chromecast_backyard
      - sensor.chromecast_kitchen
      - sensor.dlink_camera
      - sensor.driveway_camera
      - sensor.raspberry_pi

sensor:
  ###### CUSTOM ONLINE // OFFLINE TEXT FOR device_tracker
  - platform: template
    sensors:
      access_point:
        value_template: "{% if is_state('device_tracker.access_point', 'home') %}Online{% else %}Offline{% endif %}"
      wemo_link:
        value_template: "{% if is_state('device_tracker.wemo_link', 'home') %}Online{% else %}Offline{% endif %}"
      philips_hue_hub:
        value_template: "{% if is_state('device_tracker.philips_hue_hub', 'home') %}Online{% else %}Offline{% endif %}"
      chromecast_kitchen:
        value_template: "{% if is_state('device_tracker.chromecast', 'home') %}Online{% else %}Offline{% endif %}"
      chromecast_backyard:
        value_template: "{% if is_state('device_tracker.chromecast_2', 'home') %}Online{% else %}Offline{% endif %}"
      dlink_camera:
        value_template: "{% if is_state('device_tracker.baby_monitor', 'home') %}Online{% else %}Offline{% endif %}"
      driveway_camera:
        value_template: "{% if is_state('device_tracker.camera_driveway', 'home') %}Online{% else %}Offline{% endif %}"
      raspberry_pi:
        value_template: "{% if is_state('device_tracker.raspberrypi', 'home') %}Online{% else %}Offline{% endif %}"
