################################################################
## Packages / Device Status
################################################################

###### STATE CARD
group:
  device_status:
    control: hidden
    name: Device Status
    entities:
      - automation.notify_if_device_goes_offline
      - sensor.online_cameras
      - sensor.dlink_camera
      - sensor.driveway_camera
      - sensor.roomba
      - sensor.echo_dot
      - sensor.google_home
      - sensor.wemo_link
      - sensor.philips_hue_hub
      - sensor.chromecast_backyard
      - sensor.chromecast_kitchen
      - sensor.raspberry_pi
      #- sensor.raspberry_pi_zero
      - sensor.tracker_doorbell
      - sensor.bedroom_led_strip
      - sensor.room_masterbed
    #  - sensor.room_laundry_room_sensor

sensor:
  ###### CUSTOM ONLINE // OFFLINE TEXT FOR device_tracker
  - platform: template
    sensors:
      tracker_doorbell:
        friendly_name: 'Doorbell'
        value_template: "{% if is_state('device_tracker.doorbell', 'home') %}Online{% else %}Offline{% endif %}"
        icon_template: "{% if states.device_tracker.doorbell.state == 'home' %} mdi:glassdoor {% else %} mdi:alert-outline {% endif %}"
      wemo_link:
        friendly_name: 'Wemo Link'
        value_template: "{% if is_state('device_tracker.wemolink', 'home') %}Online{% else %}Offline{% endif %}"
        icon_template: "{% if states.device_tracker.wemolink.state == 'home' %} mdi:server {% else %} mdi:alert-outline {% endif %}"
      philips_hue_hub:
        friendly_name: 'Philips Hue Hub'
        value_template: "{% if is_state('device_tracker.philips_hue_hub', 'home') %}Online{% else %}Offline{% endif %}"
        icon_template: "{% if states.device_tracker.philips_hue_hub.state == 'home' %} mdi:server {% else %} mdi:alert-outline {% endif %}"
      chromecast_kitchen:
        friendly_name: 'Chromecast Kitchen'
        value_template: "{% if is_state('device_tracker.chromecast_kitchen', 'home') %}Online{% else %}Offline{% endif %}"
        icon_template: "{% if states.device_tracker.chromecast_kitchen.state == 'home' %} mdi:google-chrome {% else %} mdi:alert-outline {% endif %}"
      chromecast_backyard:
        friendly_name: 'Chromecast Backyard'
        value_template: "{% if is_state('device_tracker.chromecast_backyard', 'home') %}Online{% else %}Offline{% endif %}"
        icon_template: "{% if states.device_tracker.chromecast_backyard.state == 'home' %} mdi:google-chrome {% else %} mdi:alert-outline {% endif %}"
      dlink_camera:
        friendly_name: 'Baby Monitor'
        value_template: "{% if is_state('device_tracker.camera_baby', 'home') %}Online{% else %}Offline{% endif %}"
        icon_template: "{% if states.device_tracker.camera_baby.state == 'home' %} mdi:camera {% else %} mdi:alert-outline {% endif %}"
      driveway_camera:
        friendly_name: Driveway Camera
        value_template: "{% if is_state('device_tracker.camera_driveway', 'home') %}Online{% else %}Offline{% endif %}"
        icon_template: "{% if states.device_tracker.camera_driveway.state == 'home' %} mdi:camera {% else %} mdi:alert-outline {% endif %}"
      raspberry_pi:
        friendly_name: 'Raspberry Pi'
        value_template: "{% if is_state('device_tracker.raspibedroom', 'home') %}Online{% else %}Offline{% endif %}"
        icon_template: "{% if states.device_tracker.raspibedroom.state == 'home' %} mdi:raspberrypi {% else %} mdi:alert-outline {% endif %}"
      bedroom_led_strip:
        friendly_name: 'Bedroom Led Strip'
        value_template: "{% if is_state('device_tracker.h801_led_controller', 'home') %}Online{% else %}Offline{% endif %}"
        icon_template: "{% if states.device_tracker.h801_led_controller.state == 'home' %} mdi:chip {% else %} mdi:alert-outline {% endif %}"
      room_masterbed:
        friendly_name: 'Master Bed Sensor'
        value_template: "{% if is_state('device_tracker.room_masterbed', 'home') %}Online{% else %}Offline{% endif %}"
        icon_template: "{% if states.device_tracker.room_masterbed.state == 'home' %} mdi:chip {% else %} mdi:alert-outline {% endif %}"
      echo_dot:
        friendly_name: 'Echo Dot'
        value_template: "{% if is_state('device_tracker.echodot', 'home') %}Online{% else %}Offline{% endif %}"
        icon_template: "{% if states.device_tracker.echodot.state == 'home' %} mdi:amazon {% else %} mdi:alert-outline {% endif %}"
      raspberry_pi_zero:
        friendly_name: 'Raspberry Pi Zero'
        value_template: "{% if is_state('device_tracker.raspberry_pi_zero', 'home') %}Online{% else %}Offline{% endif %}"
        icon_template: "{% if states.device_tracker.raspberry_pi_zero.state == 'home' %} mdi:raspberrypi {% else %} mdi:alert-outline {% endif %}"
      room_laundry_room_sensor:
        friendly_name: 'Laundry Room Sensor'
        value_template: "{% if is_state('device_tracker.room_laundry_room_sensor', 'home') %}Online{% else %}Offline{% endif %}"
        icon_template: "{% if states.device_tracker.room_laundry_room_sensor.state == 'home' %} mdi:chip {% else %} mdi:alert-outline {% endif %}"
      roomba:
        friendly_name: 'Roomba'
        value_template: "{% if is_state('device_tracker.roomba', 'home') %}Online{% else %}Offline{% endif %}"
        icon_template: "{% if states.device_tracker.roomba.state == 'home' %} mdi:robot-vacuum {% else %} mdi:alert-outline {% endif %}"
      google_home:
        friendly_name: 'Google Home'
        value_template: "{% if is_state('device_tracker.google_home', 'home') %}Online{% else %}Offline{% endif %}"
        icon_template: "{% if states.device_tracker.google_home.state == 'home' %} mdi:google-assistant {% else %} mdi:alert-outline {% endif %}"

automation:
###############################################################################
# Notify when a device goes Offline or Online
###############################################################################
  - alias: Notify if Device Goes Offline
    trigger:
      platform: state
      entity_id:
        - sensor.roomba
        - sensor.tracker_doorbell
        - sensor.wemo_link
        - sensor.philips_hue_hub
        - sensor.chromecast_kitchen
        - sensor.chromecast_backyard
        - sensor.dlink_camera
        - sensor.driveway_camera
        - sensor.raspberry_pi
        - sensor.bedroom_led_strip
        - sensor.room_masterbed
        - sensor.echo_dot
        - sensor.google_home
        - sensor.raspberry_pi_zero
        - sensor.room_laundry_room_sensor
    condition:
      - condition: template
        value_template: "{% if trigger.from_state and trigger.to_state %} True {% else %} False {% endif %}"
    action:
      - service: notify.html5
        data:
          target: justin
        data_template:
          message: >
            {% if trigger.to_state.state | lower == "offline" %}
              {{ trigger.to_state.attributes.friendly_name }} has gone offline!
            {% else %}
              {{ trigger.to_state.attributes.friendly_name }} has come online!
            {% endif %}
