################################################################
## Packages / Device Status
################################################################
homeassistant:
  customize:
    #ONLINE / OFFLINE Device Tracker
    sensor.wemo_link:
      friendly_name: Wemo Link
      entity_picture: /local/custom_icons/wemo.png
    sensor.philips_hue_hub:
      friendly_name: Philips Hue Hub
      entity_picture: /local/custom_icons/huebridge.png
    sensor.chromecast_kitchen:
      friendly_name: Chromecast Kitchen
      entity_picture: /local/custom_icons/chromecast.png
    sensor.chromecast_backyard:
      friendly_name: Chromecast Backyard
      entity_picture: /local/custom_icons/chromecast.png
    sensor.dlink_camera:
      friendly_name: Baby Monitor
      icon: mdi:camera
    sensor.driveway_camera:
      friendly_name: Driveway Camera
      icon: mdi:camera
    sensor.raspberry_pi:
      friendly_name: 'Raspberry Pi'
      icon: mdi:chip
    sensor.tracker_doorbell:
      friendly_name: 'Doorbell'
      icon: mdi:chip
    sensor.bedroom_led_strip:
      friendly_name: 'Bedroom Led Strip'
      icon: mdi:chip
    sensor.laundry_room:
      friendly_name: 'Laundry Room'
      icon: mdi:chip
    sensor.echo_dot:
      friendly_name: 'Echo Dot'
      icon: mdi:chip
###### STATE CARD
group:
  device_status:
    control: hidden
    name: Device Status
    entities:
      - automation.notify_if_device_goes_offline
      - sensor.echo_dot
      - sensor.wemo_link
      - sensor.philips_hue_hub
      - sensor.chromecast_backyard
      - sensor.chromecast_kitchen
      - sensor.dlink_camera
      - sensor.driveway_camera
      - sensor.raspberry_pi
      - sensor.tracker_doorbell
      - sensor.bedroom_led_strip
      - sensor.laundry_room

sensor:
  ###### CUSTOM ONLINE // OFFLINE TEXT FOR device_tracker
  - platform: template
    sensors:
      tracker_doorbell:
        value_template: "{% if is_state('device_tracker.doorbell', 'home') %}Online{% else %}Offline{% endif %}"
      wemo_link:
        value_template: "{% if is_state('device_tracker.wemolink', 'home') %}Online{% else %}Offline{% endif %}"
      philips_hue_hub:
        value_template: "{% if is_state('device_tracker.philips_hue_hub', 'home') %}Online{% else %}Offline{% endif %}"
      chromecast_kitchen:
        value_template: "{% if is_state('device_tracker.chromecast_kitchen', 'home') %}Online{% else %}Offline{% endif %}"
      chromecast_backyard:
        value_template: "{% if is_state('device_tracker.chromecast_backyard', 'home') %}Online{% else %}Offline{% endif %}"
      dlink_camera:
        value_template: "{% if is_state('device_tracker.camera_baby', 'home') %}Online{% else %}Offline{% endif %}"
      driveway_camera:
        value_template: "{% if is_state('device_tracker.camera_driveway', 'home') %}Online{% else %}Offline{% endif %}"
      raspberry_pi:
        value_template: "{% if is_state('device_tracker.raspibedroom', 'home') %}Online{% else %}Offline{% endif %}"
      bedroom_led_strip:
        value_template: "{% if is_state('device_tracker.h801_led_controller', 'home') %}Online{% else %}Offline{% endif %}"
      laundry_room:
        value_template: "{% if is_state('device_tracker.laundry_room', 'home') %}Online{% else %}Offline{% endif %}"
      echo_dot:
        value_template: "{% if is_state('device_tracker.echodot', 'home') %}Online{% else %}Offline{% endif %}"
automation:
###############################################################################
# Notify when a device goes Offline or Online
###############################################################################
  - alias: Notify if Device Goes Offline
    trigger:
      platform: state
      entity_id:
        - sensor.tracker_doorbell
        - sensor.wemo_link
        - sensor.philips_hue_hub
        - sensor.chromecast_kitchen
        - sensor.chromecast_backyard
        - sensor.dlink_camera
        - sensor.driveway_camera
        - sensor.raspberry_pi
        - sensor.bedroom_led_strip
        - sensor.laundry_room
        - sensor.echo_dot
    condition:
      - condition: template
        value_template: "{% if trigger.from_state and trigger.to_state %} True {% else %} False {% endif %}"
    action:
      - service: notify.justin
        data_template:
          message: >
            {% if trigger.to_state.state | lower == "offline" %}
              {{ trigger.to_state.attributes.friendly_name }} has gone offline!
            {% else %}
              {{ trigger.to_state.attributes.friendly_name }} has come online!
            {% endif %}
