################################################################
## Packages / Digital Assistant
################################################################
homeassistant:
  customize:
    script.kitchen_radio:
      emulated_hue: true
      friendly_name: 'Kitchen Radio'
      google_assistant: true
      google_assistant_name: 'Kitchen Radio'
    script.pc:
      emulated_hue: true
      friendly_name: 'PC'
      google_assistant: true
      google_assistant_name: 'PC'
    script.bedroom_pc:
      emulated_hue: true
      friendly_name: 'Bedroom PC'
      google_assistant: true
      google_assistant_name: 'Bedroom PC'
    script.office_pc:
      emulated_hue: true
      friendly_name: 'Office PC'
      google_assistant: true
      google_assistant_name: 'Office PC'

google_assistant:
  project_id: !secret google_assistant_project_id
  client_id: !secret google_assistant_client_id
  access_token: !secret google_assistant_access_token
  exposed_domains:
    - switch
#    - light
#    - group

automation:
  - alias: 'google_home_volume'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.finn_sleep
    action:
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.google_home
        volume_level: >
          {% if is_state('input_boolean.finn_sleep', 'on') %} 0.50
          {% elif is_state('input_boolean.finn_sleep', 'off') %} 1
          {% endif %}
script:
###### ALEXA TURN ON or OFF PC (Living Room)
  pc:
    sequence:
      - service: switch.toggle
        entity_id: switch.living_room_pc

###### ALEXA TURN ON or OFF BEDROOM PC
  bedroom_pc:
    sequence:
      - service: switch.toggle
        entity_id: switch.bedroom_pc

###### ALEXA TURN ON or OFF OFFICE PC
  office_pc:
    sequence:
      - service: switch.toggle
        entity_id: switch.office_pc

shell_command:
  baby_cam: 'bash /home/homeassistant/.homeassistant/shell/baby_cam.sh'
