################################################################
## Packages / Doorbell
################################################################
homeassistant:
  customize:
    binary_sensor.front_doorbell:
      friendly_name: Front Doorbell
    automation.guard_dog:
      friendly_name: Guard Dogs
      icon: mdi:bone
###### STATE CARD
group:
  doorbell:
    name: Door Bell
    entities:
      - binary_sensor.front_doorbell
      - input_select.doorbell
      - automation.guard_dog

automation:
  - alias: 'notify if doorbell is pushed'
    initial_state: 'on'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: 'device_tracker.bigdrakar_justin'
          state: 'home'
        - condition: state
          entity_id: 'device_tracker.bigdrakar_nicole'
          state: 'home'
        - condition: state
          entity_id: 'input_boolean.guest'
          state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.front_doorbell
        from: 'off'
        to: 'on'
    action:
      - service: script.doorbell
      - service: notify.justin
        data:
          message: 'Someone is at the front door.'
      - service: notify.nicole
        data:
          message: 'Someone is at the front door.'

  - alias: 'guard dog'
    initial_state: 'on'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: 'input_boolean.away'
          state: 'on'
        - condition: state
          entity_id: 'input_boolean.vacation'
          state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.front_doorbell
        from: 'off'
        to: 'on'
    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.google_home
          volume_level: '1.00'
      - service: media_player.play_media
        data_template:
          entity_id: media_player.google_home
          media_content_id: http://192.168.1.250:8123/local/misc_sound/dog-barking-2-bullmastiff.mp3
          media_content_type: 'audio/mp3'
      - service: script.notify_camera
      - service: notify.justin
        data:
          message: 'Someone is at the front door, Release the Hounds!'
      - service: notify.nicole
        data:
          message: 'Someone is at the front door, Release the Hounds!'

script:
  doorbell:
    sequence:
    - condition: and
      conditions:
        - condition: template
          value_template: >
            {% if is_state('media_player.google_home', 'playing') %}
            false
            {% else %}
            true
            {% endif %}
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.google_home
        volume_level: >
          {% if is_state('sun.sun', 'above_horizon') %} '0.50'
          {% elif is_state('sun.sun', 'below_horizon') %} '0.30'
          {% endif %}
    - service: media_player.play_media
      data_template:
        entity_id: media_player.google_home
        media_content_id: >
          {% if is_state('input_select.doorbell', 'door_1') %} http://192.168.1.250:8123/local/doorbell_tones/door_1.mp3
          {% elif is_state('input_select.doorbell', 'door_ff7') %} http://192.168.1.250:8123/local/doorbell_tones/door_ff7.mp3
          {% elif is_state('input_select.doorbell', 'xmas') %} http://192.168.1.250:8123/local/doorbell_tones/xmas.mp3
          {% elif is_state('input_select.doorbell', 'R2D2') %} http://192.168.1.250:8123/local/doorbell_tones/R2D2.mp3
          {% elif is_state('input_select.doorbell', 'Ding Dong') %} http://192.168.1.250:8123/local/doorbell_tones/ding_dong.mp3
          {% elif is_state('input_select.doorbell', 'Arnold') %} http://192.168.1.250:8123/local/doorbell_tones/get-to-the-choppa.mp3
          {% elif is_state('input_select.doorbell', 'Guard Dogs') %} http://192.168.1.250:8123/local/misc_sound/dog-barking-2-bullmastiff.mp3
          {% endif %}
        media_content_type: 'audio/mp3'

input_select:
  doorbell:
    name: Tones
    options:
      - door_1
      - door_ff7
      - Ding Dong
      - xmas
      - R2D2
      - Arnold
      - Guard Dogs
    icon: mdi:bookmark-music

binary_sensor:
  - platform: mqtt
    name: 'front_doorbell'
    state_topic: "/doorbell/frontdoor/Switch"
    qos: 0
    payload_on: "0"
    payload_off: "1"
