################################################################
## Packages / Doorbell
################################################################
homeassistant:
  customize:
    binary_sensor.front_doorbell:
      friendly_name: Front Doorbell
    automation.guard_dog:
      friendly_name: Guard Dogs
      icon: mdi:bone
###### STATE CARD
group:
  doorbell:
    name: Door Bell
    entities:
      - binary_sensor.front_doorbell
      #- input_select.doorbell
      - automation.guard_dog

automation:
  - alias: 'notify if doorbell is pushed'
    initial_state: 'on'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: 'device_tracker.bigdrakar_justin'
          state: 'home'
        - condition: state
          entity_id: 'device_tracker.bigdrakar_nicole'
          state: 'home'
        - condition: state
          entity_id: 'input_boolean.guest'
          state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.front_doorbell
        from: 'off'
        to: 'on'
    action:
      - service: script.doorbell
      - service: notify.justin
        data:
          message: 'Someone is at the front door.'
      - service: notify.nicole
        data:
          message: 'Someone is at the front door.'

  - alias: 'guard dog'
    initial_state: 'on'
    condition:
      condition: or
      conditions:
        - condition: state
          entity_id: 'input_boolean.away'
          state: 'on'
        - condition: state
          entity_id: 'input_boolean.vacation'
          state: 'on'
    trigger:
      - platform: state
        entity_id: binary_sensor.front_doorbell
        from: 'off'
        to: 'on'
    action:
      - service: media_player.volume_set
        data:
          entity_id: media_player.google_home
          volume_level: 1.00
      - service: media_player.play_media
        data_template:
          entity_id: media_player.google_home
          media_content_id: "http://192.168.1.92/misc_sound/dog-barking-2-bullmastiff.mp3"
          media_content_type: 'audio/mp3'
      - service: script.notify_camera
      - service: notify.justin
        data:
          message: 'Someone is at the front door, Release the Hounds!'
      - service: notify.nicole
        data:
          message: 'Someone is at the front door, Release the Hounds!'

script:
  doorbell:
    sequence:
    - condition: and
      conditions:
        - condition: template
          value_template: >
            {% if is_state('media_player.google_home', 'playing') %}
            false
            {% else %}
            true
            {% endif %}
    - service: media_player.volume_set
      data_template:
        entity_id: media_player.google_home
        volume_level: >
          {% if is_state('input_boolean.finn_sleep', 'off') %} 1
          {% elif is_state('input_boolean.finn_sleep', 'on') %} 0.30
          {% endif %}
    - service: media_player.play_media
      data_template:
        entity_id: media_player.google_home
        media_content_id: >
            {%- if is_state('input_select.theme', "New Year's Day") -%} http://192.168.1.92/doorbell_tones/new_years.mp3
            {%- elif is_state('input_select.theme', "Groundhog Day") -%} http://192.168.1.92/doorbell_tones/groundhog_day.mp3
            {%- elif is_state('input_select.theme', "Valentine's Day") -%} http://192.168.1.92/doorbell_tones/valentines_day.mp3
            {%- elif is_state('input_select.theme', "St. Patrick's Day") -%} http://192.168.1.92/doorbell_tones/door_1.mp3
            {%- elif is_state('input_select.theme', "Good Friday") -%} http://192.168.1.92/doorbell_tones/door_1.mp3
            {%- elif is_state('input_select.theme', "Starwars Day") -%} http://192.168.1.92/doorbell_tones/R2D2.mp3
            {%- elif is_state('input_select.theme', "Easter Sunday") -%} http://192.168.1.92/doorbell_tones/door_1.mp3
            {%- elif is_state('input_select.theme', "Earth Day") -%} http://192.168.1.92/doorbell_tones/door_1.mp3
            {%- elif is_state('input_select.theme', "Mother's Day") -%} http://192.168.1.92/doorbell_tones/door_1.mp3
            {% elif is_state('input_select.theme', "Victoria Day") -%} http://192.168.1.92/doorbell_tones/door_1.mp3
            {%- elif is_state('input_select.theme', "Father's Day") -%} http://192.168.1.92/doorbell_tones/get-to-the-choppa.mp3
            {%- elif is_state('input_select.theme', "Canada Day") -%}  http://192.168.1.92/doorbell_tones/door_1.mp3
            {%- elif is_state('input_select.theme', "Labour Day") -%} http://192.168.1.92/doorbell_tones/door_1.mp3
            {%- elif is_state('input_select.theme', "Thanksgiving Day") -%} http://192.168.1.92/doorbell_tones/door_1.mp3
            {%- elif is_state('input_select.theme', "Halloween") -%} http://192.168.1.92/doorbell_tones/halloween.wav
            {%- elif is_state('input_select.theme', "Remembrance Day") -%} http://192.168.1.92/doorbell_tones/door_1.mp3
            {%- elif is_state('input_select.theme', "Christmas Eve") -%} http://192.168.1.92/doorbell_tones/xmas.mp3
            {%- elif is_state('input_select.theme', "Christmas Day") -%} http://192.168.1.92/doorbell_tones/xmas.mp3
            {%- elif is_state('input_select.theme', "Boxing Day") -%} http://192.168.1.92/doorbell_tones/xmas.mp3
            {%- elif is_state('input_select.theme', "New Year's Eve") -%} http://192.168.1.92/doorbell_tones/new_years.mp3
            {%- else -%} http://192.168.1.92/doorbell_tones/door_1.mp3
            {%- endif -%}
        media_content_type: 'audio/mp3'

# input_select:
#   doorbell:
#     name: Tones
#     options:
#       - door_1
#       - door_ff7
#       - Ding Dong
#       - xmas
#       - R2D2
#       - Arnold
#       - Guard Dogs
#     icon: mdi:bookmark-music

binary_sensor:
  - platform: mqtt
    name: 'front_doorbell'
    state_topic: "/doorbell/frontdoor/Switch"
    qos: 0
    payload_on: "0"
    payload_off: "1"
