################################################################
## Packages / Good Morning
################################################################
homeassistant:
  customize:
    script.good_morning:
      friendly_name: Good Morning
      icon: mdi:emoticon-poop

script:
  good_morning:
    sequence:
    - service: script.morning_livingroom_lights
    - service: switch.turn_off
      entity_id: switch.bedroom_fan
    - service: script.auto_cartoons
    - service: media_player.volume_set
      data:
        entity_id: media_player.kitchen
        volume_level: '0.70'
    - service: tts.google_say
      data_template:
        entity_id: media_player.kitchen
        message: "Good Morning, the weather looks like {{states('sensor.dark_sky_daily_summary')}}."
        cache: false

  morning_livingroom_lights:
    sequence:
    - condition: or
      conditions:
        - condition: state
          entity_id: 'sun.sun'
          state: 'below_horizon'
        - condition: state
          entity_id: 'sensor.dark_sky_summary'
          state: 'Cloudy'
        - condition: state
          entity_id: 'sensor.dark_sky_summary'
          state: 'Mostly Cloudy'
        - condition: state
          entity_id: 'sensor.dark_sky_summary'
          state: 'Overcast'
        - condition: state
          entity_id: 'sensor.dark_sky_summary'
          state: 'Breezy and Overcast'

    - service: light.turn_on
      data:
        entity_id:
          - light.hue_color_lamp_1:
          - light.hue_color_lamp_2:
          - light.hue_color_lamp_3:
          - light.kitchen_sink:
        brightness: 100
        color_temp: 230
