################################################################
## Packages / Good Morning
################################################################
homeassistant:
  customize:
    script.good_morning:
      emulated_hue: true
      emulated_hue_name: "Good Morning"
      friendly_name: Good Morning
      icon: mdi:emoticon-poop
    switch.bedroom_fan:
      icon: mdi:fan

script:

  good_morning:
    sequence:
    - condition: time
      after: '06:00:00'
      before: '13:00:00'
    - service: script.morning_livingroom_lights
    - service: switch.turn_off
      entity_id: switch.bedroom_fan
    - service: script.auto_cartoons
    - service: media_player.media_Stop
      entity_id: media_player.kodi_bedroom_pi
    - service: media_player.volume_set
      data:
        entity_id: media_player.kitchen
        volume_level: '0.70'
    - service: script.good_morning_tts

  good_morning_tts:
    sequence:
      - service: tts.google_say
        data_template:
          entity_id: media_player.kitchen
          message: >
            "Good Morning, the weather is {{states('sensor.dark_sky_minutely_summary')}} and {{states('sensor.dark_sky_apparent_temperature') | round}} Degrees. Today's High is {{states('sensor.dark_sky_daily_high_temperature')| round}} with a low of {{states('sensor.dark_sky_daily_low_temperature') | round}}.
            {% if is_state('sensor.nicole', 'not_home') %}
            {% elif is_state('sensor.nicole', 'home') %}
              {% if is_state('binary_sensor.workday_sensor', 'off') %}
              {% elif is_state('binary_sensor.workday_sensor', 'on') %}
              Travel time this morning is {{states('sensor.nicole_home_to_work')}} minutes and you must leave by {{((as_timestamp(now().date() ~ " 08:00:00") - (states.sensor.nicole_home_to_work.state|int * 60))|timestamp_local).split(" ")[1]}} to arrive on time.
                {% if 'rain' in states.sensor.dark_sky_hourly_summary.state %}
                Don't forget your Umbrella and
                {% else %}
                {% endif %}
                Have a nice day at work Nicole, the eye of my pie.
              {% endif %}
            {%- endif -%}
            {% if as_timestamp(now())|timestamp_custom('%A %B %d', True) == states.sensor.waste_pickup_garbage_recycling.state %}
            The next garbage pickup will be tomorrow morning.
            {% else%}
            The next garbage pickup is on {{states('sensor.waste_pickup_garbage_recycling')}}
            {% endif %}"

  morning_livingroom_lights:
    sequence:
    - condition: or
      conditions:
        - condition: state
          entity_id: 'sun.sun'
          state: 'below_horizon'
        - condition: state
          entity_id: 'sensor.dark_sky_summary'
          state: 'Cloudy'
        - condition: state
          entity_id: 'sensor.dark_sky_summary'
          state: 'Mostly Cloudy'
        - condition: state
          entity_id: 'sensor.dark_sky_summary'
          state: 'Overcast'
        - condition: state
          entity_id: 'sensor.dark_sky_summary'
          state: 'Breezy and Overcast'
    - service: script.lr_concentrate
