################################################################
## Packages / Good Morning
################################################################
homeassistant:
  customize:
    script.good_morning:
      emulated_hue: true
      emulated_hue_name: "Good Morning"
      friendly_name: Good Morning
      icon: mdi:emoticon-poop
    switch.bedroom_fan:
      icon: mdi:fan

script:

  good_morning:
    sequence:
    - condition: time
      after: '06:00:00'
      before: '13:00:00'
    - service: script.morning_livingroom_lights
    - service: switch.turn_off
      entity_id: switch.bedroom_fan
    - service: script.auto_cartoons
    - service: media_player.media_Stop
      entity_id: media_player.kodi_bedroom_pi
    - service: media_player.volume_set
      data:
        entity_id: media_player.kitchen
        volume_level: '0.70'
    - service: script.turn_on
      data_template:
        entity_id: >
          {% if is_state('binary_sensor.workday_sensor', 'off') %} script.good_morning_weekend
          {% elif is_state('binary_sensor.workday_sensor', 'on') %} script.good_morning_workday
          {% endif %}

  good_morning_workday:
    sequence:
      - service: tts.google_say
        data_template:
          entity_id: media_player.kitchen
          message: "Good Morning, the weather is {{states('sensor.dark_sky_minutely_summary')}} and {{states('sensor.dark_sky_apparent_temperature') | round}} Degrees. Today's High is {{states('sensor.dark_sky_daily_high_temperature')| round}} with a low of {{states('sensor.dark_sky_daily_low_temperature') | round}}. Travel time this morning is {{states('sensor.nicole_home_to_work')}} minutes, Have a nice day at work Nicole, the love of my life."

  good_morning_weekend:
    sequence:
      - service: tts.google_say
        data_template:
          entity_id: media_player.kitchen
          message: "Good Morning, the weather is {{states('sensor.dark_sky_minutely_summary')}} and {{states('sensor.dark_sky_apparent_temperature') | round}} Degrees. Today's High is {{states('sensor.dark_sky_daily_high_temperature')| round}} with a low of {{states('sensor.dark_sky_daily_low_temperature') | round}}. Enjoy your Weekend!"

  morning_livingroom_lights:
    sequence:
    - condition: or
      conditions:
        - condition: state
          entity_id: 'sun.sun'
          state: 'below_horizon'
        - condition: state
          entity_id: 'sensor.dark_sky_summary'
          state: 'Cloudy'
        - condition: state
          entity_id: 'sensor.dark_sky_summary'
          state: 'Mostly Cloudy'
        - condition: state
          entity_id: 'sensor.dark_sky_summary'
          state: 'Overcast'
        - condition: state
          entity_id: 'sensor.dark_sky_summary'
          state: 'Breezy and Overcast'
    - service: script.lr_concentrate
