################################################################
## Packages / Holiday
################################################################

###### STATE CARD
group:
  holiday:
    name: Holiday
    control: hidden
    entities:
     - input_select.holiday

automation:
  - alias: 'Change Current Theme'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.holiday
    action:
      - service: frontend.set_theme
        data_template:
          name: '{{states.input_select.holiday.state}}'

input_select:
  holiday:
    name: Holiday
    options:
      - "default"
      - "default_night"
      - "new_years_day"
      - "valentines_day"
      - "st_patricks_day"
      - "easter"
      - "victoria_day"
      - "canada_day"
      - "thanksgiving"
      - "halloween"
      - "christmas"
    initial: "default"
    icon: 'mdi:palette'
