################################################################
## Packages / Humidity Control
################################################################
homeassistant:
  customize:
    switch.dehumidifier:
      friendly_name: Dehumidifier
      entity_picture: /local/custom_icons/dehumidifier.png
    sensor.mold_indicator:
      friendly_name: Mold Indicator
      entity_picture: /local/custom_icons/mold.png
    automation.turn_on_dehumidifier_if_mold_sensor_is_high:
      friendly_name: Automatic Dehumidifier
      icon: mdi:water-percent

automation:
  - alias: 'Turn on dehumidifier if Mold sensor is high'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.mold_indicator
        above: 65
    action:
      - service: switch.turn_on
        entity_id: switch.dehumidifier
      - service: climate.set_fan_mode
        data:
          entity_id: climate.hallway
          fan_mode: 'on'

  - alias: 'Turn off dehumidifier if Mold sensor is low'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.mold_indicator
        below: 63
    action:
      - service: switch.turn_off
        entity_id: switch.dehumidifier
      - service: climate.set_fan_mode
        data:
          entity_id: climate.hallway
          fan_mode: 'auto'

###### NOTIFY IF MOLD SENSOR IS GREATER OR EQUAL TO 70%
  - alias: 'Notify if Mold sensor is too high'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.mold_indicator
        above: 69
    action:
      - service: notify.justin
        data_template:
          title: "Possible Mold Growth"
          message: "It's possible to have mold growth because the mold indicator is {{ states.sensor.mold_indicator.state }}"
