################################################################
## Packages / Humidity Control
################################################################
homeassistant:
  customize:
    switch.dehumidifier:
      friendly_name: Dehumidifier
      icon: mdi:water-off
    sensor.mold_indicator:
      friendly_name: Mold Indicator
      icon: mdi:chemical-weapon
    automation.dehumidifier:
      friendly_name: Automatic Dehumidifier
      icon: mdi:water-percent

###### STATE CARD
group:
  all_humidity:
    control: hidden
    name: Humidity
    entities:
      - sensor.dark_sky_humidity
      - sensor.master_bed_humidity
      - sensor.laundry_humidity
      - sensor.hallway_thermostat_humidity
      - sensor.average_humidity
      - sensor.mold_indicator
      - switch.dehumidifier
      - automation.dehumidifier

sensor:
  - platform: mold_indicator
    indoor_temp_sensor: sensor.average_whole_home
    indoor_humidity_sensor: sensor.average_humidity
    outdoor_temp_sensor: sensor.dark_sky_apparent_temperature
    calibration_factor: 1.2

###### AVERAGE HUMIDITY
  - platform: min_max
    type: mean
    name: Average Humidity
    entity_ids:
      - sensor.master_bed_humidity
    #  - sensor.laundry_humidity
      - sensor.hallway_thermostat_humidity

automation:
  - alias: 'dehumidifier'
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: >
          {% if float(states.sensor.mold_indicator.state) > float(65) or float(states.sensor.mold_indicator.state) < float(64) %} true
          {% else %} false
          {% endif %}
    action:
    - service_template: >
        {% if states.sensor.mold_indicator.state | float > 65 %} switch.turn_on
        {% else %} switch.turn_off
        {% endif %}
      entity_id: switch.dehumidifier
    - service: climate.set_fan_mode
      data_template:
        entity_id: climate.hallway
        fan_mode: >
          {% if states.sensor.mold_indicator.state | float > 65 %} 'on'
          {% else %} 'auto'
          {% endif %}

###### NOTIFY IF MOLD SENSOR IS GREATER OR EQUAL TO 70%
  - alias: 'Notify if Mold sensor is too high'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.mold_indicator
        above: 69
    action:
      - service: notify.html5
        data_template:
          title: "Possible Mold Growth"
          message: "It's possible to have mold growth because the mold indicator is {{ states.sensor.mold_indicator.state }}"
          target: "justin"
      - service: automation.turn_off
        data:
          entity_id: automation.notify_if_mold_sensor_is_too_high
      - delay: '02:00:00'
      - service: automation.turn_on
        data:
          entity_id: automation.notify_if_mold_sensor_is_too_high

  - alias: 'Notify if Dehumidifier is on too long'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: switch.dehumidifier
        to: 'on'
        for:
          hours: 2
    action:
      - service: notify.html5
        data_template:
          title: "dehumidifier Warning"
          message: "It's possible the dehumidifier water bucket if full."
          target: "justin"
