################################################################
## Packages / internet_usage
## @norien - https://github.com/Norien/Home-Assistant-Config
################################################################
homeassistant:
  customize:
    sensor.usage_billing_period:
      friendly_name: Billing Period
      icon: mdi:receipt
    sensor.usage_remaining_days:
      friendly_name: Remaining Days
      icon: mdi:calendar-clock
    sensor.usage_downloaded:
      friendly_name: Downloaded
      icon: mdi:folder-download
    sensor.usage_uploaded:
      friendly_name: Uploaded
      icon: mdi:folder-upload
    sensor.usage_total_usage:
      friendly_name: Total Usage
      icon: mdi:chart-donut
    sensor.usage_usage_cap:
      friendly_name: Usage Cap
      icon: mdi:file
    sensor.usage_remaining_usage:
      friendly_name: Remaining Usage
      icon: mdi:file
    sensor.usage_remaining_per_day:
      friendly_name: Remaining Usage Per Day
      icon: mdi:file

###### STATE CARD
group:
  internet_usage:
    name: Internet Usage
    entities:
      - sensor.usage_billing_period
      - sensor.usage_remaining_days
      - sensor.usage_downloaded
      - sensor.usage_uploaded
      - sensor.usage_total_usage
      - sensor.usage_usage_cap
      - sensor.usage_remaining_usage
      - sensor.usage_remaining_per_day

sensor:
  - platform: command_line
    command: !secret internet_usage
    name: 'usage'
    scan_interval: 21600
  - platform: template
    sensors:
      usage_downloaded:
        value_template: "{{states.sensor.usage.state.split(',')[0]}}"
        unit_of_measurement: "GB"
      usage_remaining_per_day:
        value_template: >
          {% if states.sensor.usage_remaining_days.state|int == 0 %}
          {{states.sensor.usage_remaining_usage.state}}
          {% else %}
          {{(states.sensor.usage_remaining_usage.state|int / states.sensor.usage_remaining_days.state|int|round)|round(2)}}
          {% endif %}
        unit_of_measurement: "GB"
      usage_uploaded:
        value_template: "{{states.sensor.usage.state.split(',')[1]}}"
        unit_of_measurement: "GB"
      usage_total_usage:
        value_template: "{{states.sensor.usage.state.split(',')[2]}}"
        unit_of_measurement: "GB"
      usage_usage_cap:
        value_template: "{{states.sensor.usage.state.split(',')[3]}}"
        unit_of_measurement: "GB"
      usage_remaining_usage:
        value_template: "{{states.sensor.usage.state.split(',')[4]}}"
        unit_of_measurement: "GB"
      usage_billing_period:
        value_template: >
          {% set month = as_timestamp(now())|timestamp_custom('%B', True) %}
          {% set month_prev = '{:02}'.format(as_timestamp(now())|timestamp_custom('%m', True) | int) %}
          {% set month_next = '{:02}'.format(as_timestamp(now())|timestamp_custom('%m', True) | int + 2) %}
          {% set day = as_timestamp(now())|timestamp_custom('%d', True) %}
          {% if day <= '14' %}
          {{as_timestamp(strptime(month_prev, '%m'))|timestamp_custom('%B')}} 15 - {{month}} 14
          {% else %}
          {{month}} 15 - {{as_timestamp(strptime(month_next, '%m'))|timestamp_custom('%B')}} 14
          {% endif %}
      usage_billing_period_end:
        value_template: >
          {% set month = as_timestamp(now())|timestamp_custom('%m,', True) %}
          {% set month_prev = '{:02}'.format(as_timestamp(now())|timestamp_custom('%m', True) | int) %}
          {% set month_next = '{:02}'.format(as_timestamp(now())|timestamp_custom('%m', True) | int + 2) %}
          {% set day = as_timestamp(now())|timestamp_custom('%d', True) %}
          {% if day <= '14' %}
          {{as_timestamp(now())|timestamp_custom('%Y,', True)}}{{month}}14
          {% else %}
          {{as_timestamp(now())|timestamp_custom('%Y,', True)}}{{as_timestamp(strptime(month_next, '%m'))|timestamp_custom('%m,')}}14
          {% endif %}
      usage_billing_period_today:
        value_template: >
          {% set now_date = as_timestamp(now())|timestamp_custom('%Y,%m,%d', True) %}
          {{now_date}}
  - platform: command_line
    command: "python /home/homeassistant/.homeassistant/python_scripts/usage_time_remaining.py"
    name: 'usage_remaining_days'
    unit_of_measurement: Day(s)
    scan_interval: 120

automation:
  - alias: 'Notify Internet Usage Details'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.usage_remaining_days
        below: 3
    action:
      - service: notify.justin
        data_template:
          title: "Internet Usage"
          message: "There is {{states.sensor.usage_remaining_days.state}} days left until usage meter resets and you have {{states.sensor.usage_remaining_usage.state}} GB remaining."
