################################################################
## Packages / Lights
################################################################
homeassistant:
  customize:
    light.living_room:
      friendly_name: Living Room Lights
    light.findlay_lamp:
      friendly_name: Findlay's Lamp
      icon: mdi:lamp
    script.lr_dimmed:
      emulated_hue: true
      friendly_name: 'Dimmed'
      icon: mdi:brightness-7
    script.lr_relax:
      emulated_hue: true
      friendly_name: 'Relax'
      icon: mdi:brightness-6
    script.lr_read:
      emulated_hue: true
      friendly_name: 'Read'
      icon: mdi:brightness-5
    script.lr_concentrate:
      emulated_hue: true
      friendly_name: 'Bright'
      icon: mdi:star-circle
    script.lr_springblossom:
      emulated_hue: true
      friendly_name: 'Spring blossom'
      icon: mdi:flower
    script.beach:
      emulated_hue: true
      friendly_name: 'Beach'
      icon: mdi:beach
    script.river:
      friendly_name: 'River'
      icon: mdi:fire
    script.kitchen_sink_bright:
      emulated_hue: true
      friendly_name: 'Kitchen Sink Bright'
      icon: mdi:flower
    switch.bedroom_lamps_:
      icon: mdi:lamp
      friendly_name: Bedroom Lamps
    switch.office_lightswitch:
      friendly_name: Office Light Switch
      icon: mdi:lightbulb

script:
  kitchen_sink_bright:
    sequence:
      - service: light.turn_on
        data:
          entity_id:
            light.kitchen_sink:
          brightness: 254
          rgb_color: [255,241,199]
  lr_dimmed:
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Dimmed"
  lr_relax:
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Relax"
  lr_read:
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Read"
  lr_concentrate:
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Concentrate"
  lr_springblossom:
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Spring blossom"
  beach:
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Beach"
  river:
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "river"
