################################################################
## Packages / Lights
################################################################
homeassistant:
  customize:
    light.living_room:
      friendly_name: Living Room Lights
    light.findlay_lamp:
      friendly_name: Findlay's Lamp
      icon: mdi:lamp
    script.lr_nightlight:
      friendly_name: 'Nightlight'
      icon: mdi:brightness-4
    script.lr_dimmed:
      friendly_name: 'Dimmed'
      icon: mdi:brightness-7
    script.lr_relax:
      friendly_name: 'Relax'
      icon: mdi:brightness-6
    script.lr_read:
      friendly_name: 'Read'
      icon: mdi:brightness-5
    script.lr_concentrate:
      friendly_name: 'Bright'
      icon: mdi:star-circle
    script.lr_springblossom:
      friendly_name: 'Spring blossom'
      icon: mdi:flower

script:
  lr_nightlight:
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Nightlight"
  lr_dimmed:
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Dimmed"
  lr_relax:
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Relax"
  lr_read:
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Read"
  lr_concentrate:
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Concentrate"
  lr_springblossom:
    sequence:
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Spring blossom"
