################################################################
## Packages / live scenes
################################################################
homeassistant:
  customize:
    script.aquarium_scene:
      friendly_name: 'Aquarium'
      emulated_hue_hidden: false
      icon: mdi:fish
    script.sexy_time:
      friendly_name: 'Sexy Time'
      emulated_hue_hidden: false
      icon: mdi:heart
    script.river_scene:
      friendly_name: 'River'
      emulated_hue_hidden: false
      icon: mdi:hook
    script.beach_scene:
      friendly_name: 'Beach'
      emulated_hue_hidden: false
      icon: mdi:tower-beach
    script.jungle_scene:
      friendly_name: 'Jungle'
      emulated_hue_hidden: false
      icon: mdi:paw
    script.fireplace_scene:
      friendly_name: 'Fire Place'
      emulated_hue_hidden: false
      icon: mdi:fire
    script.space_scene:
      friendly_name: 'Space'
      emulated_hue_hidden: false
      icon: mdi:earth

script:
  space_scene:
    sequence:
      - service_template: >-
          script.kodi_play_file{{ '_bootup' if is_state('switch.living_room_pc', 'off') }}
        data:
          file: "plugin://plugin.video.youtube/?action=play_video&videoid=NM2wtte1JRE"
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "space"
      - service: input_select.select_option
        data:
          entity_id: input_select.live_scene
          option: "Space"

  fireplace_scene:
    sequence:
      - service_template: >-
          script.kodi_play_file{{ '_bootup' if is_state('switch.living_room_pc', 'off') }}
        data:
          file: "c:/Users/Living Room/Videos/fireplace.mp4"
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "fire"
      - service: input_select.select_option
        data:
          entity_id: input_select.live_scene
          option: "Fire Place"

  sexy_time:
    sequence:
      - service: script.kodi_stop
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "sexy time"
      - service_template: >-
          script.kodi_play_file{{ '_bootup' if is_state('switch.living_room_pc', 'off') }}
        data:
          file: "c:/Users/Living Room/Videos/fireplace.mp4"
      - service: media_player.turn_on
        entity_id: media_player.kitchen
      - service: media_player.volume_set
        data:
          entity_id: media_player.kitchen
          volume_level: '0.20'
      - service: media_player.play_media
        data:
          entity_id: media_player.google_home
          media_content_id: "http://192.168.1.250:8123/local/misc_sound/sexy_time.mp3"
          media_content_type: "audio/mp3"
      - service: input_select.select_option
        data:
          entity_id: input_select.live_scene
          option: "Sexy Time"

  river_scene:
    sequence:
      - service: script.kodi_stop
      - service_template: >-
          script.kodi_play_file{{ '_bootup' if is_state('switch.living_room_pc', 'off') }}
        data:
          file: "c:/Users/Living Room/Videos/river.mp4"
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "river"
      - service: input_select.select_option
        data:
          entity_id: input_select.live_scene
          option: "River"

  aquarium_scene:
    sequence:
      - service: script.kodi_stop
      - service_template: >-
          script.kodi_play_file{{ '_bootup' if is_state('switch.living_room_pc', 'off') }}
        data:
          file: "c:/Users/Living Room/Videos/aquarium.mp4"
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Arctic aurora"
      - service: input_select.select_option
        data:
          entity_id: input_select.live_scene
          option: "Aquarium"

  beach_scene:
    sequence:
      - service: script.kodi_stop
      - service_template: >-
          script.kodi_play_file{{ '_bootup' if is_state('switch.living_room_pc', 'off') }}
        data:
          file: "c:/Users/Living Room/Videos/beach.mp4"
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Beach"
      - service: input_select.select_option
        data:
          entity_id: input_select.live_scene
          option: "Beach"

  jungle_scene:
    sequence:
      - service: script.kodi_stop
      - service_template: >-
          script.kodi_play_file{{ '_bootup' if is_state('switch.living_room_pc', 'off') }}
        data:
          file: "c:/Users/Living Room/Videos/jungle.mp4"
      - service: light.hue_activate_scene
        data:
          group_name: "Living Room"
          scene_name: "Jungle"
      - service: input_select.select_option
        data:
          entity_id: input_select.live_scene
          option: "Jungle"

  live_scene_off:
    sequence:
      - service: script.kodi_stop
      - service: script.lr_concentrate
      - service: media_player.turn_off
        entity_id: media_player.kitchen
      - service: input_select.select_option
        data:
          entity_id: input_select.live_scene
          option: "off"

automation:
  - alias: 'live_scene'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_select.live_scene
    action:
      service: script.turn_on
      data_template:
        entity_id: >-
          {% if is_state("input_select.live_scene", "off") %} script.live_scene_off
          {% elif is_state("input_select.live_scene", "Aquarium") %} script.aquarium_scene
          {% elif is_state("input_select.live_scene", "River") %} script.river_scene
          {% elif is_state("input_select.live_scene", "Beach") %} script.beach_scene
          {% elif is_state("input_select.live_scene", "Sexy Time") %} script.sexy_time
          {% elif is_state("input_select.live_scene", "Jungle") %} script.jungle_scene
          {% elif is_state("input_select.live_scene", "Fire Place") %} script.fireplace_scene
          {% elif is_state("input_select.live_scene", "Space") %} script.space_scene
          {% endif %}

input_select:
  live_scene:
    name: Live Scene
    options:
      - "off"
      - "Aquarium"
      - "River"
      - "Beach"
      - "Sexy Time"
      - "Jungle"
      - "Fire Place"
      - "Space"
    initial: "off"
    icon: mdi:earth
