################################################################
## Packages / Nest
################################################################

homeassistant:
  customize:
    #Nest
    climate.hallway:
      friendly_name: Nest Thermostat
      entity_picture: /local/custom_icons/nest.png
    binary_sensor.hallway_thermostat_fan:
      friendly_name: Thermostat Fan
      icon: mdi:fan
    sensor.hallway_thermostat_humidity:
      friendly_name: Indoor Humidity
      icon: mdi:water-percent
    sensor.hallway_thermostat_temperature:
      friendly_name: Hallway
    sensor.kitchen_nest_protect_battery_health:
      friendly_name: Kitchen Nest Protect Battery
      icon: mdi:battery
    sensor.hallway_thermostat_hvac_state:
      friendly_name: Thermostat HVAC State
    sensor.hallway_thermostat_operation_mode:
      friendly_name: Thermostat Operation Mode
    sensor.kitchen_nest_protect_co_status:
      entity_picture: /local/custom_icons/nestprotect.png
    sensor.kitchen_nest_protect_smoke_status:
      entity_picture: /local/custom_icons/nestprotect.png

script:
###### ALEXA TURN ON HOT / COLD / FAN
  hotter:
    sequence:
      - service: climate.set_temperature
        data_template:
          entity_id: climate.hallway
          temperature: "{{ (states.climate.hallway.attributes.current_temperature | float) +1 }}"
  colder:
    sequence:
      - service: climate.set_temperature
        data_template:
          entity_id: climate.hallway
          temperature: "{{ (states.climate.hallway.attributes.current_temperature | float) -1 }}"
  fan:
    sequence:
      - service: climate.set_fan_mode
        data:
          entity_id: climate.hallway
          fan_mode: 'auto'      
