################################################################
## Packages / Night Light
################################################################
homeassistant:
  customize:
    scene.nightlight:
      friendly_name: 'Night Light'
      icon: mdi:brightness-2

automation:
  - alias: 'Night Light'
    trigger:
      - platform: state
        entity_id: sensor.living_room_motion, sensor.dining_room_motion
        to: 'True'
    condition:
      - condition: state
        entity_id: 'sun.sun'
        state: 'below_horizon'
      - condition: time
        after: '11:59:00'
    action:
      - service: script.nightlight

script:
  nightlight:
    sequence:
     - service: light.turn_on
       data:
         entities:
           light.hue_color_lamp_1:
             brightness: 1
             color_temp: 450
           light.hue_color_lamp_2:
             brightness: 1
             color_temp: 450
           light.hue_color_lamp_3:
             brightness: 1
             color_temp: 450
           light.kitchen_sink:
             brightness: 1
             color_temp: 450
     - delay:
          minutes: 10
     - service: light.turn_off
       data:
         entities:
           light.hue_color_lamp_1:
             state: off
           light.hue_color_lamp_2:
             state: off
           light.hue_color_lamp_3:
             state: off
           light.kitchen_sink:
             state: off
