################################################################
## Packages / Notifications
################################################################

notify:
  - platform: pushbullet
    name: justin
    api_key: !secret pushbullet_api_key_justin
  - platform: pushbullet
    name: nicole
    api_key: !secret pushbullet_api_key_nicole

automation:
###### NOTIFY IF NICOLE HAS LEFT ONE OF HER WORKPLACES
  - alias: Notify If Left Work
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.bigdrakar_nicole
        from: 'Work Westmount'
        to: 'not_home'
      - platform: state
        entity_id: device_tracker.bigdrakar_nicole
        from: 'Work Old South'
        to: 'not_home'
      - platform: state
        entity_id: device_tracker.bigdrakar_nicole
        from: 'Work Whitehills'
        to: 'not_home'
    action:
      - service: notify.justin
        data_template:
          message: >
            {{ trigger.to_state.attributes.friendly_name }} has left work.

###### NOTIFY IF VACATION MODE toggled
  - alias: 'Notify Vacation Mode'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.vacation
    action:
      - service: notify.justin
        data:
          message: 'Vacation Mode is now {{states.input_boolean.vacation.state}}'

###### NOTIFY IF GUEST MODE toggled
  - alias: 'Notify Guest Mode'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.guest
    action:
      - service: notify.justin
        data:
          message: 'Guest Mode is now {{states.input_boolean.guest.state}}'

###### NOTIFY IF UPDATE TO HOME ASSISTANT IS Available and then POST an issue to github to update it
  - alias: 'notify if update available'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.current_version
    action:
      - service: shell_command.post_git_issue
      - service: notify.justin
        data:
          message: 'Update for Home Assistant is available. Visit https://github.com/home-assistant/home-assistant/releases for details.'

###### NOTIFY IF IP CHANGES
  - alias: Notify Of New External IP
    initial_state: 'on'
    trigger:
      platform: state
      entity_id: sensor.external_ip
    condition:
      - condition: template
        value_template: "{% if trigger.from_state and trigger.to_state %} True {% else %} False {% endif %}"
    action:
      - service: notify.justin
        data_template:
          message: "Your External IP changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}"

# Announce new devices on the network. Thanks 2 @robotsandcakes
  - alias: "Notify if New device connected"
    initial_state: 'on'
    trigger:
      - platform: event
        event_type: device_tracker_new_device
    action:
      - service: notify.justin
        data_template:
          message: >
            New entity ID {{ trigger.event.data.entity_id }} and hostname {{ trigger.event.data.host_name }}

shell_command:
  post_git_issue: 'python /home/homeassistant/.homeassistant/shell/make_github_issue.py'
