################################################################
## Packages / Notifications
################################################################

notify:
  - platform: pushbullet
    name: justin
    api_key: !secret pushbullet_api_key_justin
  - platform: pushbullet
    name: nicole
    api_key: !secret pushbullet_api_key_nicole
  - name: email
    platform: smtp
    server: smtp.gmail.com
    port: 587
    timeout: 15
    sender: !secret email
    starttls: true
    username: !secret email
    password: !secret email_pass
    recipient:
      - !secret email
      - !secret her_email

automation:
###### NOTIFY IF NICOLE HAS LEFT ONE OF HER WORKPLACES
  - alias: Notify If Left Work
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.bigdrakar_nicole
        from: 'Work Westmount'
        to: 'not_home'
      - platform: state
        entity_id: device_tracker.bigdrakar_nicole
        from: 'Work Old South'
        to: 'not_home'
      - platform: state
        entity_id: device_tracker.bigdrakar_nicole
        from: 'Work Whitehills'
        to: 'not_home'
    action:
      - service: notify.justin
        data_template:
          message: >
            {{ trigger.to_state.attributes.friendly_name }} has left work.

###### NOTIFY IF VACATION MODE IS ACTIVATED
  - alias: 'Notify if Vacation is On'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.vacation
        from: 'off'
        to: 'on'
    action:
      - service: notify.justin
        data:
          message: 'Vacation Mode has been Activated'

###### NOTIFY IF VACATION MODE IS DEACTIVATED
  - alias: 'Notify if Vacation is Off'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.vacation
        from: 'on'
        to: 'off'
    action:
      - service: notify.justin
        data:
          message: 'Vacation Mode has been Deactivated'

###### NOTIFY IF UPDATE TO HOME ASSISTANT IS Available and then POST an issue to github to update it
  - alias: 'notify if update available'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.current_version
    action:
      - service: shell_command.post_git_issue
      - service: notify.justin
        data:
          message: 'Update for Home Assistant is available. Visit https://github.com/home-assistant/home-assistant/releases for details.'

###### NOTIFY IF IP CHANGES
  - alias: Notify Of New External IP
    trigger:
      platform: state
      entity_id: sensor.external_ip
    condition:
      - condition: template
        value_template: "{% if trigger.from_state and trigger.to_state %} True {% else %} False {% endif %}"
    action:
      - service: notify.justin
        data_template:
          message: "Your External IP changed from {{ trigger.from_state.state }} to {{ trigger.to_state.state }}"

shell_command:
  post_git_issue: 'python /home/homeassistant/.homeassistant/shell/make_github_issue.py'
