################################################################
## Packages / Remote Raspberry PI Zero
################################################################
homeassistant:
  customize:
    # SYSTEM
    sensor.pi_zero_uptime:
      friendly_name: System uptime
      icon: mdi:timer
    # MEMORY
    sensor.pi_zero_ram:
      friendly_name: RAM
      icon: mdi:chip
    # NETWORK
    sensor.pi_zero_ip:
      friendly_name: Internal IP
      icon: mdi:earth
    # TEMPERATURE
    sensor.pi_zero_temperature:
      friendly_name: Temperature
    # PROCESSES

###### STATE CARD
group:
  pi_zero:
    name: Pi Zero Status
    control: hidden
    entities:
     # SYSTEM
     - sensor.pi_zero_release
     - sensor.pi_zero_kernel
     - sensor.pi_zero_uptime
     - sensor.pi_zero_last_boot_day
     - sensor.pi_zero_last_boot_time
     - sensor.pi_zero_users
     - sensor.pi_zero_server_time
     # LOAD AVERAGE
     - sensor.pi_zero_one_minute
     - sensor.pi_zero_five_minutes
     - sensor.pi_zero_fifteen_minutes
     # CPU
     - sensor.pi_zero_cpu_model
     - sensor.pi_zero_cpu_frequency
     # MEMORY
     - sensor.pi_zero_mem_total
     - sensor.pi_zero_mem_used
     - sensor.pi_zero_ram
     # NETWORK
     - sensor.pi_zero_ip
     - sensor.pi_zero_mac
     - sensor.pi_zero_hostname
     # DISK SPACE
     - sensor.pi_zero_disk_size
     - sensor.pi_zero_disk_used
     - sensor.pi_zero_disk_available
     - sensor.pi_zero_disk_use
     # TEMPERATURE
     - sensor.pi_zero_temperature
     # PROCESSES
     - sensor.pi_zero_process_total
     - sensor.pi_zero_process_running
     - sensor.pi_zero_ssh
     - sensor.pi_zero_smbd
     - sensor.pi_zero_bluetooth

sensor:
###### SYSTEM
  - platform: rest
    name: pi_zero_release
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.system.release }}'

  - platform: rest
    name: pi_zero_kernel
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.system.kernel }}'

  - platform: rest
    name: pi_zero_uptime
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.system.uptime }}'

  - platform: rest
    name: pi_zero_last_boot_day
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.system.last_boot_day }}'

  - platform: rest
    name: pi_zero_last_boot_time
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.system.last_boot_time }}'

  - platform: rest
    name: pi_zero_users
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.system.users }}'

  - platform: rest
    name: pi_zero_server_time
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.system.server_time }}'

###### LOAD AVERAGE
  - platform: rest
    name: pi_zero_one_minute
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.load_average.one_minute }}'
    unit_of_measurement: '%'

  - platform: rest
    name: pi_zero_five_minutes
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.load_average.five_minutes }}'
    unit_of_measurement: '%'

  - platform: rest
    name: pi_zero_fifteen_minutes
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.load_average.fifteen_minutes }}'
    unit_of_measurement: '%'

###### CPU
  - platform: rest
    name: pi_zero_cpu_model
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.cpu.cpu_model }}'

  - platform: rest
    name: pi_zero_cpu_frequency
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.cpu.cpu_frequency }}'
    unit_of_measurement: 'MHZ'

###### MEMORY
  - platform: rest
    name: pi_zero_mem_total
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.memory.total }}'
    unit_of_measurement: 'MB'

  - platform: rest
    name: pi_zero_mem_used
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.memory.used }}'
    unit_of_measurement: 'MB'
# Custom RAM Template to display used / total in a single line
  - platform: template
    sensors:
      pi_zero_ram:
        value_template: "{{states.sensor.pi_zero_mem_used.state|int}} MB / {{states.sensor.pi_zero_mem_total.state}} MB"

###### NETWORK
  - platform: rest
    name: pi_zero_ip
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.network.lan_ip }}'

  - platform: rest
    name: pi_zero_mac
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.network.lan_mac }}'

  - platform: rest
    name: pi_zero_hostname
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.network.hostname }}'

###### DISK SPACE
  - platform: rest
    name: pi_zero_disk_size
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.disk_space.disk_space_size }}'
    unit_of_measurement: 'GB'

  - platform: rest
    name: pi_zero_disk_used
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.disk_space.disk_space_used }}'
    unit_of_measurement: 'GB'

  - platform: rest
    name: pi_zero_disk_available
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.disk_space.disk_space_available }}'
    unit_of_measurement: 'GB'

  - platform: rest
    name: pi_zero_disk_use
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.disk_space.disk_space_use }}'
    unit_of_measurement: '%'

###### TEMPERATURE
  - platform: rest
    name: pi_zero_temperature
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.temperature.system_temp }}'
    unit_of_measurement: '°C'

###### PROCESSES
  - platform: rest
    name: pi_zero_process_total
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.processes.process_total }}'

  - platform: rest
    name: pi_zero_process_running
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.processes.process_running }}'

  - platform: rest
    name: pi_zero_ssh
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.processes.ssh }}'

  - platform: rest
    name: pi_zero_smbd
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.processes.smbd }}'

  - platform: rest
    name: pi_zero_bluetooth
    resource: http://192.168.1.70/stats.json
    value_template: '{{ value_json.processes.bluetooth }}'
