################################################################
## Packages / Presence
################################################################
homeassistant:
  customize:
    # GOOGLE TRAVEL TIME SENSORS
    sensor.nicole_phone_to_home:
      friendly_name: 'Nicole Phone to Home'
      icon: mdi:car
    sensor.nicole_home_to_work:
      friendly_name: 'Nicole Home to Work'
      icon: mdi:car
    sensor.life360_sensor:
      friendly_name: Life 360

###### STATE CARD
group:
  presence:
    control: hidden
    name: Presence
    entities:
      - group.justin
      - group.nicole
      - input_boolean.guest
      - input_boolean.away
      - input_boolean.vacation
  justin:
    name: Justin
    icon: mdi:human
    entities:
      - input_boolean.justin
      - device_tracker.justin_router
      - device_tracker.justin_justin
  nicole:
    name: Nicole
    icon: mdi:human-female
    entities:
      - input_boolean.nicole
      - device_tracker.nicole_router
      - device_tracker.nicole_nicole
      - sensor.nicole_phone_to_home

automation:
###### Mark Justin away or home
  - alias: 'Mark Justin Away'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.justin_router
        to: 'not_home'
        for:
          minutes: 10
      - platform: state
        entity_id: device_tracker.justin_justin
        to: 'not_home'
    condition:
      condition: state
      entity_id: input_boolean.justin
      state: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.justin

  - alias: 'Mark Justin Home'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.justin_router
        to: 'home'
      - platform: state
        entity_id: device_tracker.justin_justin
        to: 'home'
    condition:
      condition: state
      entity_id: input_boolean.justin
      state: 'off'
    action:
       service: homeassistant.turn_on
       entity_id: input_boolean.justin

  ###### Mark Nicole away or home
  - alias: 'Mark Nicole Away'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.nicole_router
        to: 'not_home'
        for:
          minutes: 10
      - platform: state
        entity_id: device_tracker.nicole_nicole
        to: 'not_home'
    condition:
      condition: state
      entity_id: input_boolean.nicole
      state: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.nicole

  - alias: 'Mark Nicole Home'
    trigger:
      - platform: state
        entity_id: device_tracker.nicole_router
        to: 'home'
      - platform: state
        entity_id: device_tracker.nicole_nicole
        to: 'home'
    condition:
      condition: state
      entity_id: input_boolean.nicole
      state: 'off'
    action:
       service: homeassistant.turn_on
       entity_id: input_boolean.nicole

#-----------------------------------------------
############# AWAY
  - alias: Set Away Mode on
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: group.justin, group.nicole
        to: 'off'
    condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: 'group.justin'
          state: 'off'
        - condition: state
          entity_id: 'group.nicole'
          state: 'off'
        - condition: state
          entity_id: 'input_boolean.guest'
          state: 'off'
        - condition: state
          entity_id: 'input_boolean.away'
          state: 'off'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.away
      - service: notify.justin
        data:
          message: 'Nobody is home, All switches and lights have been turned OFF. The alarm is armed'
      - service: script.all_off

############# HOME
  - alias: 'Set Away Mode off'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: group.justin, group.nicole
        to: 'on'
    condition:
    - condition: state
      entity_id: input_boolean.away
      state: 'on'
    - condition: or
      conditions:
        - condition: state
          entity_id: 'group.justin'
          state: 'on'
        - condition: state
          entity_id: 'group.nicole'
          state: 'on'
        - condition: state
          entity_id: 'input_boolean.guest'
          state: 'on'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.away
      - service: notify.justin
        data:
          message: 'Alarm is disarmed, Welcome Home'
###### SET NEST HOME
      - service: climate.set_away_mode
        data:
          entity_id: climate.hallway
          away_mode: 'false'
script:
  all_off:
    sequence:
  ##### BEDROOM
      - service: switch.turn_off
        entity_id: switch.bedroom_pc_off
      - service: switch.turn_off
        entity_id: switch.led_strip
      - service: switch.turn_off
        entity_id: switch.bedroom_lamps_
      - service: switch.turn_off
        entity_id: switch.bedroom_fan
  ###### LIVINGROOM/KITCHEN
      - service: switch.turn_off
        entity_id: switch.living_room_pc
      - service: light.turn_off
        entity_id: light.living_room
      - service: light.turn_off
        entity_id: light.kitchen_sink
      - service: media_player.turn_off
        entity_id: media_player.kitchen
  ###### BACKYARD
      - service: light.turn_off
        entity_id: light.deck_lights
      - service: media_player.turn_off
        entity_id: media_player.backyard
      - service: switch.turn_off
        entity_id: switch.patio_amplifier
  ###### OFFICE
      - service: switch.turn_off
        entity_id: switch.office_lightswitch
      - service: switch.turn_off
        entity_id: switch.office_pc
  ###### FINDLAYS ROOM
      - service: light.turn_off
        entity_id: light.findlay_lamp
  ###### SET NEST AWAY
      - service: climate.set_away_mode
        data:
          entity_id: climate.hallway
          away_mode: 'true'
  ###### HALLWAY
      - service: light.turn_off
        entity_id: light.hallway

###### MODES / PEOPLE
input_boolean:
  guest:
    name: Guest
    icon: mdi:account-box
    initial: off
  vacation:
    name: Vacation
    icon: mdi:sunglasses
    initial: off
  away:
    name: Away
    icon: mdi:account-off
    initial: off
  justin:
    name: Justin
    icon: mdi:account
  nicole:
    name: Nicole
    icon: mdi:account

###### Sensors
sensor:
###### GOOGLE TRAVEL TIME
  - platform: google_travel_time
    name: Nicole Phone To Home
    api_key: !secret google_secret
    origin: device_tracker.nicole_nicole
    destination: zone.home

  - platform: life360
    username: !secret life360_username
    password: !secret life360_password
    mqtt_topic: "/life360/data"
    scan_interval: 60
