################################################################
## Packages / Presence
################################################################
homeassistant:
  customize:
    device_tracker.bigdrakar_justin:
      friendly_name: Justin Owntracks
    device_tracker.bigdrakar_nicole:
      friendly_name: Nicole Owntracks
    device_tracker.android262071b676d4d855:
      friendly_name: Justin Netgear
    device_tracker.androidc3a6fa8dea348d9e:
      friendly_name: Nicole Netgear

###### STATE CARD
group:
  presence:
    control: hidden
    name: Presence
    entities:
     - device_tracker.bigdrakar_justin
     - device_tracker.bigdrakar_nicole
     - sensor.nicole_phone_to_home
     - sensor.nicole_home_to_work
     - input_boolean.guest
     - input_boolean.away
     - input_boolean.vacation

automation:
############# AWAY
  - alias: Set Away Mode on
    initial_state: 'on'
    condition:
    - condition: and
      conditions:
        - condition: state
          entity_id: 'device_tracker.bigdrakar_justin'
          state: 'not_home'
        - condition: state
          entity_id: 'device_tracker.bigdrakar_nicole'
          state: 'not_home'
        - condition: state
          entity_id: 'input_boolean.guest'
          state: 'off'
        - condition: state
          entity_id: 'input_boolean.away'
          state: 'off'
    trigger:
      - platform: state
        entity_id: device_tracker.bigdrakar_justin, device_tracker.bigdrakar_nicole
        to: 'not_home'
    action:
      - service: homeassistant.turn_on
        entity_id: input_boolean.away
      - service: notify.justin
        data:
          message: 'Nobody is home, All switches and lights have been turned OFF. The alarm is armed'
##### BEDROOM
      - service: switch.turn_off
        entity_id: switch.bedroom_pc_off
      - service: switch.turn_off
        entity_id: switch.led_strip
      - service: switch.turn_off
        entity_id: switch.bedroom_lamps_
      - service: switch.turn_off
        entity_id: switch.bedroom_fan
  ###### LIVINGROOM/KITCHEN
      - service: switch.turn_off
        entity_id: switch.living_room_pc_off
      - service: light.turn_off
        entity_id: light.living_room
      - service: light.turn_off
        entity_id: light.kitchen_sink
      - service: media_player.turn_off
        entity_id: media_player.kitchen
  ###### BACKYARD
      - service: light.turn_off
        entity_id: light.deck_lights
      - service: media_player.turn_off
        entity_id: media_player.backyard
      - service: switch.turn_off
        entity_id: switch.patio_amplifier
  ###### OFFICE
      - service: switch.turn_off
        entity_id: switch.office_lightswitch
      - service: switch.turn_off
        entity_id: switch.office_pc
 ###### FINDLAYS ROOM
      - service: light.turn_off
        entity_id: light.findlay_lamp
###### SET NEST AWAY
      - service: climate.set_away_mode
        data:
          entity_id: climate.hallway
          away_mode: 'true'

############# HOME
  - alias: 'Set Away Mode off'
    initial_state: 'on'
    condition:
    - condition: state
      entity_id: input_boolean.away
      state: 'on'
    - condition: or
      conditions:
        - condition: state
          entity_id: 'device_tracker.bigdrakar_justin'
          state: 'home'
        - condition: state
          entity_id: 'device_tracker.bigdrakar_nicole'
          state: 'home'
        - condition: state
          entity_id: 'input_boolean.guest'
          state: 'on'
    trigger:
      - platform: state
        entity_id: device_tracker.bigdrakar_justin, device_tracker.bigdrakar_nicole
        to: 'home'
    action:
      - service: homeassistant.turn_off
        entity_id: input_boolean.away
      - service: notify.justin
        data:
          message: 'Alarm is disarmed, Welcome Home'
###### SET NEST HOME
      - service: climate.set_away_mode
        data:
          entity_id: climate.hallway
          away_mode: 'false'

###### MODES / PEOPLE
input_boolean:
  guest:
    name: Guest
    icon: mdi:account-box
    initial: off
  vacation:
    name: Vacation
    icon: mdi:sunglasses
    initial: off
  away:
    name: Away
    icon: mdi:account-off
    initial: off
  justin:
    name: Justin
    initial: off
  nicole:
    name: Nicole
    initial: off
