################################################################
## Packages / Processes
## Dependencies / System Monitor
################################################################
homeassistant:
  customize:
    sensor.process_glances:
      friendly_name: 'Glances'
    sensor.process_mosquitto:
      friendly_name: 'Mosquitto'
    sensor.process_mysqld:
      friendly_name: 'MySQL'
    sensor.process_dnsmasq:
      friendly_name: 'Pi-Hole'

###### STATE CARD
group:
  processes:
    name: Processes
    control: hidden
    entities:
      - automation.notify_if_service_goes_offline
      - sensor.process_glances
      - sensor.process_mosquitto
      - sensor.process_mysqld
      - sensor.process_dnsmasq
      - sensor.gif_maker_status
      - sensor.process_flic
      - sensor.master_bed_kodi
      - sensor.process_life360
      - sensor.processes_kodi_cpu

sensor:
  - platform: systemmonitor
    resources:
      - type: process
        arg: glances
      - type: process
        arg: mosquitto
      - type: process
        arg: mysqld
      - type: process
        arg: dnsmasq

  - platform: template
    sensors:
      master_bed_kodi:
        friendly_name: 'Master Bedroom Kodi'
        value_template: "{% if is_state('media_player.kodi_bedroom_pi', 'off') %}off{% else %}on{% endif %}"
        icon_template: "{% if states.media_player.kodi_bedroom_pi.state == 'off' %} mdi:alert-outline {% else %} mdi:kodi {% endif %}"
      process_flic:
        friendly_name: 'Flic'
        value_template: "{% if is_state('sensor.master_bed_flic', 'offline') %}off{% else %}on{% endif %}"
        icon_template: "{% if states.sensor.master_bed_flic.state == 'online' %} mdi:memory {% else %} mdi:alert-outline {% endif %}"
      process_life360:
        friendly_name: 'Life 360'
        value_template: "{% if is_state('sensor.life360_sensor', 'running') %}on{% else %}off{% endif %}"
        icon_template: "{% if states.sensor.life360_sensor.state == 'running' %} mdi:account-convert {% else %} mdi:alert-outline {% endif %}"


  - platform: command_line
    command: ps -eo pcpu -eo command |grep kodi-x11
    name: processes_kodi_cpu
    value_template: '{{value [0:4]|float}}'
    unit_of_measurement: '%'
    scan_interval: 60

  - platform: command_line
    name: master_bed_flic
    command: 'curl -s http://192.168.1.92/stats.json'
    value_template: '{{ value_json.processes.flic }}'
    scan_interval: 900

automation:
###############################################################################
# Notify when a service goes Offline or Online
###############################################################################
  - alias: Notify if Service Goes Offline
    trigger:
      platform: state
      entity_id:
        - sensor.process_glances
        - sensor.process_mosquitto
        - sensor.process_mysqld
        - sensor.process_dnsmasq
        - sensor.gif_maker_status
        - sensor.master_bed_kodi
        - sensor.master_bed_flic
        - sensor.life360_sensor

    condition:
      - condition: template
        value_template: "{% if trigger.from_state and trigger.to_state %} True {% else %} False {% endif %}"
    action:
      - service: notify.html5
        data:
          target: justin
        data_template:
          message: >
            {% if trigger.to_state.state | lower == "off" %}
              {{ trigger.to_state.attributes.friendly_name }} has gone offline!
            {% else %}
              {{ trigger.to_state.attributes.friendly_name }} has come online!
            {% endif %}
