################################################################
## Packages / Processes
## Dependencies / System Monitor
################################################################
homeassistant:
  customize:
    sensor.process_glances:
      friendly_name: 'Glances'
    sensor.process_mosquitto:
      friendly_name: 'Mosquitto'
    sensor.process_mysqld:
      friendly_name: 'MySQL'
    sensor.process_dnsmasq:
      friendly_name: 'Pi-Hole'
    sensor.raspberry_pi:
      friendly_name: 'Raspberry Pi'
      icon: mdi:chip
###### STATE CARD
group:
  processes:
    name: Processes
    control: hidden
    entities:
      - sensor.process_glances
      - sensor.process_mosquitto
      - sensor.process_mysqld
      - sensor.process_dnsmasq
      - sensor.raspberry_pi

sensor:
  - platform: systemmonitor
    resources:
      - type: process
        arg: glances
      - type: process
        arg: mosquitto
      - type: process
        arg: mysqld
      - type: process
        arg: dnsmasq

  ###### CUSTOM ON // OFF TEXT FOR device_tracker
  - platform: template
    sensors:
      raspberry_pi:
        value_template: "{% if is_state('device_tracker.raspberrypi', 'home') %}on{% else %}off{% endif %}"
