################################################################
## Packages / Processes
## Dependencies / System Monitor
################################################################
homeassistant:
  customize:
    sensor.process_glances:
      friendly_name: 'Glances'
    sensor.process_mosquitto:
      friendly_name: 'Mosquitto'
    sensor.process_mysqld:
      friendly_name: 'MySQL'
    sensor.process_dnsmasq:
      friendly_name: 'Pi-Hole'
    sensor.process_plex_media_server:
      friendly_name: 'Plex'
      icon: mdi:plex
    sensor.plex:
      friendly_name: 'Current Users'
      icon: mdi:account
    sensor.kodi_version:
      friendly_name: 'Version'
      icon: mdi:package-variant
    sensor.process_kodix11:
      friendly_name: 'Living Room Kodi'
      icon: mdi:kodi

###### STATE CARD
group:
  processes:
    name: Processes
    control: hidden
    entities:
      - automation.notify_if_service_goes_offline
      - sensor.process_glances
      - sensor.process_mosquitto
      - group.mysql
      - group.plex
      - group.pihole
      - sensor.gif_maker_status
    #  - sensor.process_flic
      - group.process_kodi_livingroom
    #  - sensor.master_bed_kodi
      - sensor.process_life360
  process_kodi_livingroom:
    name: Living Room Kodi
    control: hidden
    icon: mdi:kodi
    entities:
      - sensor.process_kodix11
      - sensor.kodi_livingroom_state
      - sensor.kodi_version
      - script.kodi_restart
  mysql:
    name: MySQL
    control: hidden
    icon: mdi:memory
    entities:
      - sensor.process_mysqld
      - sensor.mysql_database_size
      - sensor.mysql_version
  plex:
    name: Plex
    control: hidden
    icon: mdi:plex
    entities:
      - sensor.process_plex_media_server
      - sensor.plex
      - sensor.plex_version
  pihole:
    name: pihole
    control: hidden
    icon: mdi:memory
    entities:
      - sensor.process_dnsmasq
      - sensor.pi_hole_version
      - script.pihole_update

sensor:
  - platform: systemmonitor
    resources:
      - type: process
        arg: glances
      - type: process
        arg: mosquitto
      - type: process
        arg: mysqld
      - type: process
        arg: dnsmasq
      - type: process
        arg: Plex Media Server
      - type: process
        arg: kodi-x11

  - platform: template
    sensors:
      kodi_livingroom_state:
        friendly_name: 'State'
        value_template: "{{states.media_player.kodi_livingroom.state}}"
        icon_template: "{% if states.media_player.livingroom.state == 'off' %} mdi:alert-outline {% else %} mdi:kodi {% endif %}"
      # master_bed_kodi:
      #   friendly_name: 'Master Bedroom Kodi'
      #   value_template: "{% if is_state('media_player.kodi_bedroom_pi', 'off') %}off{% else %}on{% endif %}"
      #   icon_template: "{% if states.media_player.kodi_bedroom_pi.state == 'off' %} mdi:alert-outline {% else %} mdi:kodi {% endif %}"
      # process_flic:
      #   friendly_name: 'Flic'
      #   value_template: "{% if is_state('sensor.master_bed_flic', 'offline') %}off{% else %}on{% endif %}"
      #   icon_template: "{% if states.sensor.master_bed_flic.state == 'online' %} mdi:memory {% else %} mdi:alert-outline {% endif %}"
      process_life360:
        friendly_name: 'Life 360'
        value_template: "{% if is_state('sensor.life360_sensor', 'running') %}on{% else %}off{% endif %}"
        icon_template: "{% if states.sensor.life360_sensor.state == 'running' %} mdi:account-convert {% else %} mdi:alert-outline {% endif %}"

  - platform: command_line
    command: kodi --version | head -1 | awk  '{print $1" "$2}'
    name: kodi_version
    scan_interval: 86400

  # - platform: command_line
  #   name: master_bed_flic
  #   command: 'curl -s http://192.168.1.92/stats.json'
  #   value_template: '{{ value_json.processes.flic }}'
  #   scan_interval: 900

automation:
###############################################################################
# Notify when a service goes Offline or Online
###############################################################################
  - alias: Notify if Service Goes Offline
    trigger:
      platform: state
      entity_id:
        - sensor.process_glances
        - sensor.process_mosquitto
        - sensor.process_mysqld
        - sensor.process_dnsmasq
        - sensor.gif_maker_status
        # - sensor.master_bed_kodi
        # - sensor.master_bed_flic
        - sensor.life360_sensor
    condition:
      - condition: template
        value_template: "{% if trigger.from_state and trigger.to_state %} True {% else %} False {% endif %}"
    action:
      - service: notify.html5
        data:
          target: justin
        data_template:
          message: >
            {% if trigger.to_state.state | lower == "off" %}
              {{ trigger.to_state.attributes.friendly_name }} has gone offline!
            {% else %}
              {{ trigger.to_state.attributes.friendly_name }} has come online!
            {% endif %}
