################################################################
## Packages / Findlays Room
################################################################
homeassistant:
  customize:
    input_boolean.finn_sleep:
      emulated_hue_hidden: false
    script.finn_sleep:
      google_assistant: true
      google_assistant_name: 'Sleep'
    automation.light_finn_sleep:
      friendly_name: 'Keep Light Off'
      icon: mdi:brightness-4
    automation.finn_temp_watchdog:
      friendly_name: 'Temperature Watch Dog'
      icon: mdi:thermometer-lines

###### STATE CARD
group:
  findlays_room:
    control: hidden
    name: "Findlay's Room"
    entities:
      - light.findlays_room
      - input_boolean.finn_sleep
      - automation.light_finn_sleep
      - group.findlays_room_temp
  findlays_room_temp:
    name: 'Temperature Watch Dog'
    entities:
      - automation.finn_temp_watchdog
      - sensor.findlay_room_temperature

script:
  finn_sleep:
    sequence:
      - service: input_boolean.toggle
        entity_id: input_boolean.finn_sleep

automation:
  - alias: 'finn_temp_watchdog'
    initial_state: 'on'
    trigger:
      - platform: numeric_state
        entity_id: sensor.findlay_room_temperature
        below: 19
    condition:
      - condition: state
        entity_id: 'input_boolean.finn_sleep'
        state: 'on'
    action:
      - service: climate.set_temperature
        data_template:
          entity_id: climate.hallway
          temperature: "{{ (states.climate.hallway.attributes.current_temperature | float) +0.5 }}"

  - alias: 'light_finn_sleep'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.finn_sleep
        to: 'on'
      - platform: template
        value_template: "{% if is_state('light.findlays_room', 'on') %}true{% endif %}"
    condition:
      - condition: state
        entity_id: 'input_boolean.finn_sleep'
        state: 'on'
    action:
      - service: light.turn_off
        data:
          entity_id: light.findlays_room

  - alias: 'light_finn'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.findlay_room_motion
        to: 'True'
      - platform: numeric_state
        entity_id: 'sensor.findlay_room_lux'
        below: 45
    condition:
      - condition: numeric_state
        entity_id: 'sensor.findlay_room_lux'
        below: 45
      - condition: state
        entity_id: 'input_boolean.finn_sleep'
        state: 'off'
      - condition: state
        entity_id: sensor.findlay_room_motion
        state: 'True'
    action:
      - service: light.turn_on
        data_template:
          entity_id: light.findlays_room
          brightness: >
            {% if (as_timestamp(now()) - as_timestamp(states.input_boolean.finn_sleep.last_changed)) > 600 %} 250
            {% else %}
            100
            {% endif %}

  - alias: 'light_finn_off'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.findlay_room_motion
        to: 'False'
        for:
          hours: 0
          minutes: 3
          seconds: 0
      - platform: numeric_state
        entity_id: 'sensor.findlay_room_lux'
        above: 45
    action:
      - service: light.turn_off
        data:
          entity_id: light.findlays_room

input_boolean:
  finn_sleep:
    name: 'Sleep'
    icon: mdi:sleep
