################################################################
## Packages / Findlays Room
################################################################
homeassistant:
  customize:
    input_boolean.finn_sleep:
      emulated_hue: true
    automation.light_finn_sleep:
      friendly_name: 'Keep Light Off'
      icon: mdi:brightness-4

###### STATE CARD
group:
  findlays_room:
    control: hidden
    name: "Findlay's Room"
    entities:
      - light.findlays_room
      - input_boolean.finn_sleep
      - automation.light_finn_sleep

automation:
  - alias: 'light_finn_sleep'
    initial_state: 'on'
    trigger:
      - platform: template
        value_template: "{% if is_state('light.findlays_room', 'on') %}true{% endif %}"
    condition:
      - condition: state
        entity_id: 'input_boolean.finn_sleep'
        state: 'on'
    action:
      - service: light.turn_off
        data:
          entity_id: light.findlays_room

  - alias: 'light_finn'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.findlay_room_motion
        to: 'True'
      - platform: numeric_state
        entity_id: 'sensor.findlay_room_lux'
        below: 45
    condition:
      - condition: numeric_state
        entity_id: 'sensor.findlay_room_lux'
        below: 45
      - condition: state
        entity_id: 'input_boolean.finn_sleep'
        state: 'off'
      - condition: state
        entity_id: sensor.findlay_room_motion
        state: 'True'
    action:
      - service: light.turn_on
        data:
          entity_id: light.findlays_room

  - alias: 'light_finn_off'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.findlay_room_motion
        to: 'False'
        for:
          hours: 0
          minutes: 3
          seconds: 0
      - platform: numeric_state
        entity_id: 'sensor.findlay_room_lux'
        above: 45
    action:
      - service: light.turn_off
        data:
          entity_id: light.findlays_room

input_boolean:
  finn_sleep:
    name: 'Sleep'
    icon: mdi:sleep
