################################################################
## Packages / Sensors
################################################################
homeassistant:
  customize:
    #philips hue motion sensors
    ######Findlays Room
    sensor.findlay_room_motion:
      friendly_name: "Findlay's Room"
      icon: mdi:run
    sensor.findlay_room_lux:
      icon: mdi:theme-light-dark
    sensor.findlay_room_temperature:
      icon: mdi:thermometer
      friendly_name: Findlay's Room

    ######Living room
    sensor.living_room_motion:
      friendly_name: "Living Room"
      icon: mdi:run
    sensor.living_room_lux:
      icon: mdi:theme-light-dark
    sensor.living_room_temperature:
      icon: mdi:thermometer
      friendly_name: Living Room

    ######Dining Room
    sensor.dining_room_motion:
      friendly_name: "Dining Room"
      icon: mdi:run
    sensor.dining_room_lux:
      icon: mdi:theme-light-dark
    sensor.dining_room_temperature:
      icon: mdi:thermometer
      friendly_name: Dining Room

###### STATE CARDS
group:
  motion_sensors:
    name: Motion
    entities:
     - sensor.findlay_room_motion
     - sensor.living_room_motion
     - sensor.dining_room_motion
     - binary_sensor.room_masterbed_motion
     - binary_sensor.laundry_motion
  all_temps:
    name: Temperature
    entities:
     - sensor.dark_sky_temperature
     - sensor.hallway_thermostat_temperature
     - sensor.findlay_room_temperature
     - sensor.office_temperature
     - sensor.master_bed_temperature
     - sensor.living_room_temperature
     - sensor.dining_room_temperature
     - sensor.laundry_temperature
     - sensor.average_whole_home
  lux:
    name: Light Level
    entities:
      - sensor.findlay_room_lux
      - sensor.living_room_lux
      - sensor.dining_room_lux

###### BINARY SENSORS ------------------------------------------
binary_sensor:
  - platform: workday
    country: CA
###### SENSORS -------------------------------------------------
sensor:
  - platform: plex
    token: !secret plex_token
    username: !secret plex_username
    password: !secret plex_password

  #####FINDLAYS ROOM SENSOR & DIMMER
  - platform: rest
    resource: !secret finn_room_lux
    value_template: "{{(10 ** (float (value_json.state.lightlevel) / 10000) -1) | round (1)}} "
    unit_of_measurement: Lux
    name: 'Findlay Room Lux'
    scan_interval: 120

  - platform: rest
    resource: !secret finn_room_motion
    value_template: '{{ value_json.state.presence }}'
    name: 'Findlay Room Motion'
    scan_interval: 2
    device_class: motion

  - platform: rest
    resource: !secret finn_room_temp
    value_template: '{{ (value_json.state.temperature | float / 100 + 1.6) | round(1) }}'
    unit_of_measurement: °C
    name: 'Findlay Room Temperature'
    scan_interval: 120

  #####LIVING ROOM SENSOR & DIMMER
  - platform: rest
    resource: !secret livingroom_lux
    value_template: "{{(10 ** (float (value_json.state.lightlevel) / 10000) -1) | round (1)}} "
    unit_of_measurement: Lux
    name: 'Living Room Lux'
    scan_interval: 700

  - platform: rest
    resource: !secret livingroom_motion
    value_template: '{{ value_json.state.presence }}'
    name: 'Living Room Motion'
    scan_interval: 2
    device_class: motion

  - platform: rest
    resource: !secret livingroom_temp
    value_template: '{{ (value_json.state.temperature | float / 100 + 0.35) | round(1) }}'
    unit_of_measurement: °C
    name: 'Living Room Temperature'
    scan_interval: 120

  #####DINING ROOM SENSOR
  - platform: rest
    resource: !secret dining_room_lux
    value_template: "{{(10 ** (float (value_json.state.lightlevel) / 10000) -1) | round (1)}} "
    unit_of_measurement: Lux
    name: 'Dining Room Lux'
    scan_interval: 700

  - platform: rest
    resource: !secret dining_room_motion
    value_template: '{{ value_json.state.presence }}'
    name: 'Dining Room Motion'
    scan_interval: 2
    device_class: motion

  - platform: rest
    resource: !secret dining_room_temp
    value_template: '{{ (value_json.state.temperature | float / 100) | round(1) }}'
    unit_of_measurement: °C
    name: 'Dining Room Temperature'
    scan_interval: 120

  ######DATE TIME
  - platform: yr
  - platform: time_date
    display_options:
      - "date_time"
      - 'time'

###### AVERAGE TEMPERATURE
  - platform: min_max
    type: mean
    name: Average Whole Home
    entity_ids:
      - sensor.hallway_thermostat_temperature
      - sensor.findlay_room_temperature
      - sensor.master_bed_temperature
      - sensor.living_room_temperature
      - sensor.dining_room_temperature
     # - sensor.laundry_temperature

###### DAY OF THE WEEK
  - platform: template
    sensors:
      date_weekday:
        value_template: "{{as_timestamp(now())|timestamp_custom('%A', True)}}"

###### MONTH OF THE YEAR
  - platform: template
    sensors:
      date_month:
        value_template: "{{as_timestamp(now())|timestamp_custom('%B', True)}}"

###### test
  - platform: template
    sensors:
      online_cameras:
        value_template: >
          {% set comma = joiner(", ") %}
          {%- for state in states.device_tracker -%}
          {%- if state.state == 'home' and state.name[0:7] == 'camera_' -%}
          {{ comma() }}{{state.name[7:]}}
          {%-endif -%}
          {%- endfor %}
