################################################################
## Packages / Sensors
################################################################
homeassistant:
  customize:
    #philips hue motion sensors
    ######Findlays Room
    sensor.findlay_room_motion:
      friendly_name: "Findlay's Room"
      icon: mdi:run
    sensor.findlay_room_lux:
      icon: mdi:theme-light-dark
    sensor.findlay_room_temperature:
      icon: mdi:thermometer
      friendly_name: Findlay's Room
    sensor.findlay_room_motion_sensor_battery_level:
      friendly_name: Findlay's Room Sensor
      icon: mdi:battery

    ######Living room
    sensor.living_room_motion:
      friendly_name: "Living Room"
      icon: mdi:run
    sensor.living_room_lux:
      icon: mdi:theme-light-dark
    sensor.living_room_temperature:
      icon: mdi:thermometer
      friendly_name: Living Room
    sensor.living_room_motion_sensor_battery_level:
      friendly_name: Living Room Sensor
      icon: mdi:battery

    ######Dining Room
    sensor.dining_room_motion:
      friendly_name: "Dining Room"
      icon: mdi:run
    sensor.dining_room_lux:
      icon: mdi:theme-light-dark
    sensor.dining_room_temperature:
      icon: mdi:thermometer
      friendly_name: Dining Room
    sensor.dining_room_motion_sensor_battery_level:
      friendly_name: Dining Room Sensor
      icon: mdi:battery

    #Philips Hue Switches
    sensor.living_room_dimmer_switch:
      friendly_name: Living Room Dimmer Switch
      icon: mdi:battery
    sensor.findlays_room_dimmer_switch:
      friendly_name: Findlay's Dimmer Switch
      icon: mdi:battery

    # dynamic battery names
    sensor.justins_g5_battery_dynamic:
      friendly_name: Justin's Cellphone
    sensor.nicoles_s7_battery_dynamic:
      friendly_name: Nicole's Cellphone

    #Custom data template sensor
    sensor.average_house_temp:
      friendly_name: Average Whole Home
      icon: mdi:thermometer

    # GOOGLE TRAVEL TIME SENSORS
    sensor.nicole_phone_to_home:
      friendly_name: 'Nicole Phone to Home'
      icon: mdi:car
    sensor.nicole_home_to_work:
      friendly_name: 'Nicole Home to Work'
      icon: mdi:car

###### STATE CARDS
group:
  motion_sensors:
    name: Motion
    entities:
     - sensor.findlay_room_motion
     - sensor.living_room_motion
     - sensor.dining_room_motion
     #- sensor.driveway_motion
     - binary_sensor.room_masterbed_motion
     - binary_sensor.laundry_motion
  all_temps:
    name: Temperature
    entities:
     - sensor.dark_sky_temperature
     - sensor.hallway_thermostat_temperature
     - sensor.findlay_room_temperature
     - sensor.master_bed_temperature
     - sensor.living_room_temperature
     - sensor.dining_room_temperature
     - sensor.laundry_temperature
     - sensor.average_house_temp
  sensor_battery_levels:
    name: Battery Levels
    entities:
     - sensor.kitchen_nest_protect_battery_health
     - sensor.findlay_room_motion_sensor_battery_level
     - sensor.living_room_motion_sensor_battery_level
     - sensor.dining_room_motion_sensor_battery_level
     - sensor.findlays_room_dimmer_switch
     - sensor.living_room_dimmer_switch
    # - sensor.driveway_battery_level
     - sensor.justins_g5_battery_dynamic
     - sensor.nicoles_s7_battery_dynamic
  lux:
    name: Light Level
    entities:
      - sensor.findlay_room_lux
      - sensor.living_room_lux
      - sensor.dining_room_lux

###### BINARY SENSORS ------------------------------------------
binary_sensor:
  - platform: workday
    country: CA
###### SENSORS -------------------------------------------------
sensor:
  - platform: steam_online
    api_key: !secret steam_api
    accounts:
      - id: !secret steam_user
        entity_id: "account"

  #####FINDLAYS ROOM SENSOR & DIMMER
  - platform: rest
    resource: !secret finn_room_lux
    value_template: "{{(10 ** (float (value_json.state.lightlevel) / 10000) -1) | round (1)}} "
    unit_of_measurement: Lux
    name: 'Findlay Room Lux'
    scan_interval: 80

  - platform: rest
    resource: !secret finn_room_motion
    value_template: '{{ value_json.state.presence }}'
    name: 'Findlay Room Motion'
    scan_interval: 2
    device_class: motion

  - platform: rest
    resource: !secret finn_room_temp
    value_template: '{{ (value_json.state.temperature | float / 100 + 1.6) | round(1) }}'
    unit_of_measurement: 째C
    name: 'Findlay Room Temperature'
    scan_interval: 120

  - platform: rest
    resource: !secret finn_room_sensor_battery
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Findlay Room Motion Sensor Battery Level'

  - platform: rest
    resource: !secret finn_room_switch_battery
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Findlays Room Dimmer Switch'

  #####LIVING ROOM SENSOR & DIMMER
  - platform: rest
    resource: !secret livingroom_lux
    value_template: "{{(10 ** (float (value_json.state.lightlevel) / 10000) -1) | round (1)}} "
    unit_of_measurement: Lux
    name: 'Living Room Lux'
    scan_interval: 600

  - platform: rest
    resource: !secret livingroom_motion
    value_template: '{{ value_json.state.presence }}'
    name: 'Living Room Motion'
    scan_interval: 2
    device_class: motion

  - platform: rest
    resource: !secret livingroom_temp
    value_template: '{{ (value_json.state.temperature | float / 100 + 0.35) | round(1) }}'
    unit_of_measurement: 째C
    name: 'Living Room Temperature'
    scan_interval: 120

  - platform: rest
    resource: !secret livingroom_sensor_battery
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Living Room Motion Sensor Battery Level'

  - platform: rest
    resource: !secret livingroom_sensor_battery
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Living Room Dimmer Switch'

  #####DINING ROOM SENSOR
  - platform: rest
    resource: !secret dining_room_lux
    value_template: "{{(10 ** (float (value_json.state.lightlevel) / 10000) -1) | round (1)}} "
    unit_of_measurement: Lux
    name: 'Dining Room Lux'
    scan_interval: 600

  - platform: rest
    resource: !secret dining_room_motion
    value_template: '{{ value_json.state.presence }}'
    name: 'Dining Room Motion'
    scan_interval: 2
    device_class: motion

  - platform: rest
    resource: !secret dining_room_temp
    value_template: '{{ (value_json.state.temperature | float / 100) | round(1) }}'
    unit_of_measurement: 째C
    name: 'Dining Room Temperature'
    scan_interval: 120

  - platform: rest
    resource: !secret dining_room_sensor_battery
    value_template: '{{ value_json.config.battery }}'
    unit_of_measurement: '%'
    scan_interval: 1800
    name: 'Dining Room Motion Sensor Battery Level'

  ######DATE TIME
  - platform: yr
  - platform: time_date
    display_options:
      - "date_time"

  ##### Owntracks Battery Tracker for Cell Phones
  - platform: mqtt
    state_topic: "owntracks/bigdrakar/justin"
    name: "Justin's G5 Battery"
    unit_of_measurement: "%"
    value_template: '{{ value_json.batt }}'
  - platform: template
    sensors:
      justins_g5_battery_dynamic:
        unit_of_measurement: '%'
        entity_id: sensor.justins_g5_battery
        value_template: "{{ (states.sensor.justins_g5_battery.state)|int|default('unknown') }}"
        icon_template: >-
          {% set battery_level = states('sensor.justins_g5_battery')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

  - platform: mqtt
    state_topic: "owntracks/bigdrakar/nicole"
    name: "Nicole's S7 Battery"
    unit_of_measurement: "%"
    value_template: '{{ value_json.batt }}'
  - platform: template
    sensors:
      nicoles_s7_battery_dynamic:
        unit_of_measurement: '%'
        entity_id: sensor.nicoles_s7_battery
        value_template: "{{ (states.sensor.nicoles_s7_battery.state)|int|default('unknown') }}"
        icon_template: >-
          {% set battery_level = states('sensor.nicoles_s7_battery')|int('unknown') %}
          {% set battery_round = (battery_level|int / 10)|int * 10 %}
          {% if battery_level == 'unknown' %}
            mdi:battery-unknown
          {% else %}
            {% if battery_round >= 100 %}
              mdi:battery
            {% elif battery_round > 0 %}
              mdi:battery-{{ battery_round }}
            {% else %}
              mdi:battery-alert
            {% endif %}
          {% endif %}

###### AVERAGE TEMP
  - platform: template
    sensors:
      average_house_temp:
            unit_of_measurement: "째C"
            value_template: >-
              {{ ((float(states.sensor.findlay_room_temperature.state) + float(states.sensor.hallway_thermostat_temperature.state) + float(states.sensor.living_room_temperature.state) + float(states.sensor.dining_room_temperature.state) + float(states.sensor.master_bed_temperature.state)) / 5) | default(0) | round(1) }}

###### DAY OF THE WEEK
  - platform: template
    sensors:
      date_weekday:
        value_template: "{{as_timestamp(now())|timestamp_custom('%A', True)}}"

###### MONTH OF THE YEAR
  - platform: template
    sensors:
      date_month:
        value_template: "{{as_timestamp(now())|timestamp_custom('%B', True)}}"

###### DAY OF THE MONTH
  - platform: template
    sensors:
      date_day:
        value_template: "{{as_timestamp(now())|timestamp_custom('%d', True)}}"

###### GOOGLE TRAVEL TIME
  - platform: google_travel_time
    name: Nicole Phone To Home
    api_key: !secret google_secret
    origin: device_tracker.bigdrakar_nicole
    destination: zone.home
