homeassistant:
  customize:

    light.living_room_lamp:
      color_set: false
    light.couch:
      color_set: false
    light.kitchen_sink:
      color_set: false
    light.hue_color_lamp_1:
      color_set: false
    light.hue_color_lamp_2:
      color_set: false
    light.hue_go:
      color_set: false
    input_boolean.dummy:
      friendly_name: Dummy Input Boolean
      hidden: true
      color_set: false
      rgb_color: [100,100,100]
      brightness: 255

    script.set_random_color_2_all_bulbs:
      hidden: false
    script.light_set_color:
      hidden: false

group:
  Family Room Hue Bulbs:
    entities:
     - light.living_room_lamp
     - light.couch
     - light.kitchen_sink
     - light.hue_color_lamp_1
     - light.hue_color_lamp_3
     - light.hue_go

input_boolean:
  dummy:
    name: Dummy Input Boolean
    initial: on
    icon: mdi:file-chart

script:
  set_random_color_2_all_bulbs:
    sequence:
      - service: script.light_set_color
        data_template:
          entity_id: >
            {%- macro get_next_entity_id() -%}
              {%- for item in states.group.family_room_hue_bulbs.attributes.entity_id if is_state_attr(item, 'color_set', False) -%}
                {{- "," if not loop.first-}}{{- item -}}{{-endif-}}
              {%- endfor -%}
            {%- endmacro -%}
            {%- set entity_ids = get_next_entity_id() -%}
            {% if entity_ids | trim != "" %}
              {%- if entity_ids.split(',') | length > 0 -%}
                {{- entity_ids .split(',')[0] -}}
              {%- endif -%}
            {% endif %}
          r: '{{ "{0:d}".format(range(210, 238)|random) }}'
          g: '{{ "{0:d}".format(range(100, 132)|random) }}'
          b: '{{ "{0:d}".format(range(240, 255)|random) }}'
          brightness: 255

  light_set_color:
    sequence:
      - condition: template
        value_template: '{{ entity_id | trim != "" }}'
      - condition: template
        value_template: '{{ brightness | trim != "" }}'
      - condition: template
        value_template: '{{ rgb_color | trim != "" }}'
      - service: light.turn_on
        data_template:
          entity_id: '{{ entity_id }}'
          brightness: '{{ brightness | int }}'
          rgb_color:  '[{{r}}, {{g}}, {{b}}]'
          color_set: true
      - condition: template
        value_template: >
            {%- macro get_next_entity_id() -%}
              {%- for item in states.group.family_room_hue_bulbs.attributes.entity_id if is_state_attr(item, 'color_set', False) -%}
                {{- "," if not loop.first-}}{{- item -}}{{-endif-}}
              {%- endfor -%}
            {%- endmacro -%}
            {%- set entity_ids = get_next_entity_id() -%}
            {% if entity_ids | trim != "" and entity_ids.split(',') | length | int == 0 %}
              false
            {% else %}
              true
            {% endif %}
      - service_template: script.set_random_color_2_all_bulbs
