################################################################
## Packages / Utilities
################################################################
homeassistant:
  customize:
    script.update_ha:
      friendly_name: Update Home Assistant
      icon: mdi:package-variant
    script.restart_ha:
      friendly_name: Restart Home Assistant
      icon: mdi:restart
    script.clear_log:
      friendly_name: 'Clear Log File'
      icon: mdi:eraser

script:
  update_ha:
    sequence:
      - service: shell_command.update_ha
  restart_ha:
    sequence:
      - service: shell_command.del_log
      - service: shell_command.restart_ha
  clear_log:
     sequence:
       - service: shell_command.del_log

automation:
  - alias: "Startup Notification"
    initial_state: 'on'
    trigger:
      platform: event
      event_type: homeassistant_start
    action:
      service: notify.justin
      data:
        title: "HomeAssistant Startup"
        message: "Home Assistant restarted."

sensor:
  - platform: command_line
    command: python3 -c "import requests; print(requests.get('https://pypi.python.org/pypi/homeassistant/json').json()['info']['version'])"
    name: Current Version
  - platform: command_line
    name: Installed Version
    command: /srv/homeassistant/bin/hass --version
  - platform: template
    sensors:
      ha_last_restart:
        value_template: '{{ as_timestamp(states.automation.startup_notification.attributes.last_triggered) | timestamp_custom("%b %d %X") }}'
        friendly_name: Last Restart

shell_command:
  update_ha: 'sudo bash /home/homeassistant/.homeassistant/shell/update_ha.sh </dev/null >> /home/homeassistant/.homeassistant/shell/update_ha.log 2>&1 &'
  restart_ha: 'sudo bash /home/homeassistant/.homeassistant/shell/restart_ha.sh'
  del_log: 'sudo bash /home/homeassistant/.homeassistant/shell/del_log.sh'
