################################################################
## Packages / Vacuum
## Roomba 690 SW: 3.2.10
## blid and password found with https://github.com/koalazak/dorita980#how-to-get-your-usernameblid-and-password
################################################################
homeassistant:
  customize:
    automation.vacuum_auto:
      friendly_name: Automatic Vacuum
      icon: mdi:roomba
    vacuum.roomba:
      emulated_hue_hidden: false
      emulated_hue_name: "roomba"
      google_assistant: true
      google_assistant_name: "roomba"

###### STATE CARD
group:
  vacuum:
    name: Vacuum
    control: hidden
    entities:
     - vacuum.roomba
     - automation.vacuum_auto
     - sensor.roomba_status
     - sensor.battery_roomba

vacuum:
  - platform: roomba
    host: !secret roomba_ip
    username: !secret roomba_blid
    password: !secret roomba_pass

# Toggle vacuum as we come and go
automation:
  - alias: 'vacuum_auto'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.away
        to: 'on'
      - platform: state
        entity_id: input_boolean.away
        to: 'off'
    action:
      - service: vacuum.toggle
        entity_id: vacuum.roomba

  - alias: 'Vacuum Alert'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: sensor.roomba_status
        to: 'Stuck'
    action:      
      - service: notify.html5
        data_template:
          target: justin
          message:  "Roomba is Stuck"
sensor:
###### Pull out the battery data for use in battery package.
  - platform: template
    sensors:
      battery_roomba:
        friendly_name: 'Roomba'
        value_template: "{{ states.vacuum.roomba.attributes.battery_level }}"
        unit_of_measurement: '%'
        icon_template: "{{ states.vacuum.roomba.attributes.battery_icon }}"
      roomba_status:
        friendly_name: 'Status'
        value_template: "{{ states.vacuum.roomba.attributes.status }}"
        icon_template: "{{ states.vacuum.roomba.attributes.icon }}"
