################################################################
## Packages / Welcome Home
################################################################

automation:
  - alias: 'welcome_home_lights'
    initial_state: 'on'
    trigger:
      - platform: state
        entity_id: input_boolean.away
        to: 'off'
    action:
# OUTDOOR PORCH LIGHT IS SET ON WHEN HOME FROM THEME PACKAGE
      - service_template: >
          {% if states.sensor.living_room_lux.state | float < 45 %} switch.turn_on
          {% else %} switch.turn_off
          {% endif %}
        entity_id: light.living_room
      - wait_template: "{{ states.sensor.living_room_motion.state == 'True' }}"
      - service: tts.google_say
        data_template:
          entity_id: media_player.google_home
          message: "Welcome Home"
